/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.serializer;

import dk.itu.smdp.survey.serializer.AbstractDslSyntacticSequencer;

@SuppressWarnings("all")
public class DslSyntacticSequencer extends AbstractDslSyntacticSequencer {
}
