/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.generator;

import com.google.common.base.Objects;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.Functions.Function0;
import org.eclipse.xtext.xbase.lib.IntegerRange;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import survey.Answer;
import survey.AnswerTemplate;
import survey.AnswerTemplateRef;
import survey.Date;
import survey.Group;
import survey.HasOptions;
import survey.Item;
import survey.Multiple;
import survey.Option;
import survey.Question;
import survey.Scale;
import survey.Single;
import survey.Survey;
import survey.Table;
import survey.TableQuestion;
import survey.Text;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class DslGenerator implements IGenerator {
  private int nextId = 0;
  
  private HashMap<Question,String> idMap = new Function0<HashMap<Question,String>>() {
    public HashMap<Question,String> apply() {
      HashMap<Question,String> _hashMap = new HashMap<Question, String>();
      return _hashMap;
    }
  }.apply();
  
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    EList<EObject> _contents = resource.getContents();
    EObject _head = IterableExtensions.<EObject>head(_contents);
    Survey survey = ((Survey) _head);
    this.genPhp(survey, fsa);
    this.genLatex(survey, fsa);
  }
  
  public void genPhp(final Survey survey, final IFileSystemAccess fsa) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<title>");
    String _title = survey.getTitle();
    _builder.append(_title, "        ");
    _builder.append("</title>");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("<!-- Bootstrap -->");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<link href=\"http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<style media=\"screen\" type=\"text/css\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(".group { margin-bottom: 20px; margin-top: 50px; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("input[type=number] { text-align: right; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("h2 + p.lead { font-size: 21px; margin-bottom: 30px; margin-top: -15px; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("label.control-label { font-size: 16px; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("label .help-block { font-size: 85%; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(".table { min-width: 50%; width: auto; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("table.scale td { padding: 8px; text-align: center; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("table.scale .top td { padding-bottom: 0; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("table.scale .bottom { border-top: 1px solid #DDD; border-bottom: 1px solid #DDD; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("form .form-group + .form-group { padding-top: 15px; }");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("form hr { margin-top: 30px; }");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<!--[if lt IE 9]>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<script src=\"//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<script src=\"//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<![endif]-->");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</head>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<body>");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<div class=\"row\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<div> <h1>");
    String _title_1 = survey.getTitle();
    _builder.append(_title_1, "                ");
    _builder.append("</h1> <p class=\"lead\">");
    String _description = survey.getDescription();
    _builder.append(_description, "                ");
    _builder.append("</p> </div>");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("<form role=\"form\">");
    _builder.newLine();
    {
      EList<Item> _items = survey.getItems();
      for(final Item item : _items) {
        _builder.append("\t\t\t\t\t");
        String _genHtml = this.genHtml(item, false);
        _builder.append(_genHtml, "					");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("                    ");
    _builder.append("<hr/>");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("<div class=\"form-group\">");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<button type=\"submit\" class=\"btn btn-success btn-lg\">Submit</button>");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<button type=\"reset\" class=\"btn btn-danger btn-lg\">Reset</button>");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</form>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<!-- jQuery (necessary for Bootstrap\'s JavaScript plugins) -->");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<!-- Include all compiled plugins (below), or include individual files as needed -->");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<script src=\"https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$( document ).ready(function() {");
    _builder.newLine();
    _builder.append("            \t");
    _builder.append("$(\'.input-group.date\').datepicker({");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("autoclose: true,");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("todayHighlight: true,");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("todayBtn: true");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("});");
    _builder.newLine();
    _builder.append("            \t");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("$(\"[data-depends-on]\").each(function() {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("var _this = $(this);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("_this.hide();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("var dependsOnId = $(this).attr(\"data-depends-on\");");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("var dependsOn = $(\"#\" + dependsOnId);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("switch (dependsOn.attr(\"type\")) {");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("case \"radio\":");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("                                ");
    _builder.append("$(\"input[name=\" + dependsOn.attr(\"name\") + \"]:radio\").change(function () {");
    _builder.newLine();
    _builder.append("                                    ");
    _builder.append("if ($(this).attr(\"id\") == dependsOnId)");
    _builder.newLine();
    _builder.append("                                        ");
    _builder.append("_this.show();");
    _builder.newLine();
    _builder.append("                                    ");
    _builder.append("else");
    _builder.newLine();
    _builder.append("                                        ");
    _builder.append("_this.hide();");
    _builder.newLine();
    _builder.append("                                ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    String template = _builder.toString();
    String _xifexpression = null;
    String _name = survey.getName();
    boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_name);
    if (_isNullOrEmpty) {
      _xifexpression = "survey.html";
    } else {
      String _name_1 = survey.getName();
      String _plus = (_name_1 + ".html");
      _xifexpression = _plus;
    }
    final String filename = _xifexpression;
    fsa.generateFile(filename, template);
  }
  
  public String getUniqueId(final Question question) {
    int _plus = (this.nextId + 1);
    this.nextId = _plus;
    String id = ("input" + Integer.valueOf(this.nextId));
    this.idMap.put(question, id);
    return id;
  }
  
  protected String _genHtml(final Group group, final boolean required) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"group\">");
    _builder.newLine();
    {
      String _title = group.getTitle();
      boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_title);
      boolean _not = (!_isNullOrEmpty);
      if (_not) {
        _builder.append("    ");
        _builder.append("<h2 id=\"grid\" class=\"page-header\">");
        String _title_1 = group.getTitle();
        _builder.append(_title_1, "    ");
        _builder.append("</h2>");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      String _description = group.getDescription();
      boolean _isNullOrEmpty_1 = StringExtensions.isNullOrEmpty(_description);
      boolean _not_1 = (!_isNullOrEmpty_1);
      if (_not_1) {
        _builder.append("    ");
        _builder.append("<p class=\"lead\">");
        String _description_1 = group.getDescription();
        _builder.append(_description_1, "    ");
        _builder.append("</p>");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      EList<Question> _questions = group.getQuestions();
      for(final Question question : _questions) {
        _builder.append("\t");
        boolean _isRequired = group.isRequired();
        String _genHtml = this.genHtml(question, _isRequired);
        _builder.append(_genHtml, "	");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("</div>");
    _builder.newLine();
    return _builder.toString();
  }
  
  public CharSequence genHeader(final Question question, final boolean required) {
    CharSequence _genHeader = this.genHeader(question, required, "");
    return _genHeader;
  }
  
  public CharSequence genHeader(final Question question, final boolean required, final String extraAttributes) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<label class=\"control-label\" ");
    _builder.append(extraAttributes, "");
    _builder.append(">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t        ");
    String _title = question.getTitle();
    _builder.append(_title, "	        ");
    _builder.append(" ");
    CharSequence _genRequiredLabel = this.genRequiredLabel(question, required);
    _builder.append(_genRequiredLabel, "	        ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t        ");
    {
      String _description = question.getDescription();
      boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_description);
      boolean _not = (!_isNullOrEmpty);
      if (_not) {
        _builder.append("<p class=\"help-block\">");
        String _description_1 = question.getDescription();
        _builder.append(_description_1, "	        ");
        _builder.append("</p>");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("</label>");
    _builder.newLine();
    return _builder;
  }
  
  protected String _genHtml(final Text question, final boolean required) {
    String _xblockexpression = null;
    {
      String id = this.getUniqueId(question);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"form-group\">");
      _builder.newLine();
      _builder.append("\t");
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("for=\"");
      _builder_1.append(id, "");
      _builder_1.append("\"");
      CharSequence _genHeader = this.genHeader(question, required, _builder_1.toString());
      _builder.append(_genHeader, "	");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("<div class=\"row\">");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("<div class=\"col-xs-4\">");
      _builder.newLine();
      {
        boolean _isMultiline = question.isMultiline();
        boolean _not = (!_isMultiline);
        if (_not) {
          _builder.append("\t\t\t");
          _builder.append("<input class=\"form-control\" id=\"");
          _builder.append(id, "			");
          _builder.append("\" ");
          CharSequence _genRequiredAttr = this.genRequiredAttr(question, required);
          _builder.append(_genRequiredAttr, "			");
          _builder.append(">");
          _builder.newLineIfNotEmpty();
        } else {
          _builder.append("\t\t\t");
          _builder.append("<textarea class=\"form-control\" id=\"");
          _builder.append(id, "			");
          _builder.append("\" rows=\"3\" ");
          CharSequence _genRequiredAttr_1 = this.genRequiredAttr(question, required);
          _builder.append(_genRequiredAttr_1, "			");
          _builder.append("></textarea>");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("        ");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final Scale question, final boolean required) {
    String _xblockexpression = null;
    {
      String id = this.getUniqueId(question);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"group\">");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("<div class=\"form-group\">");
      _builder.newLine();
      _builder.append("    \t");
      CharSequence _genHeader = this.genHeader(question, required);
      _builder.append(_genHeader, "    	");
      _builder.newLineIfNotEmpty();
      _builder.append("        ");
      _builder.append("<table class=\"scale\">");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("<tr class=\"top\">");
      _builder.newLine();
      {
        String _minLabel = question.getMinLabel();
        boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_minLabel);
        boolean _not = (!_isNullOrEmpty);
        if (_not) {
          _builder.append("            \t");
          _builder.append("<td></td>");
          _builder.newLine();
        }
      }
      {
        int _min = question.getMin();
        int _max = question.getMax();
        IntegerRange _upTo = new IntegerRange(_min, _max);
        boolean _hasElements = false;
        for(final Integer i : _upTo) {
          if (!_hasElements) {
            _hasElements = true;
            _builder.append("<td>", "                ");
          } else {
            _builder.appendImmediate("</td><td>", "                ");
          }
          _builder.append("                ");
          _builder.append("<label for=\"");
          _builder.append(id, "                ");
          _builder.append("_");
          _builder.append(i, "                ");
          _builder.append("\">");
          _builder.append(i, "                ");
          _builder.append("</label>");
          _builder.newLineIfNotEmpty();
        }
        if (_hasElements) {
          _builder.append("</td>", "                ");
        }
      }
      {
        String _minLabel_1 = question.getMinLabel();
        boolean _isNullOrEmpty_1 = StringExtensions.isNullOrEmpty(_minLabel_1);
        boolean _not_1 = (!_isNullOrEmpty_1);
        if (_not_1) {
          _builder.append("            \t");
          _builder.append("<td></td>");
          _builder.newLine();
        }
      }
      _builder.append("            ");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("<tr class=\"bottom\">");
      _builder.newLine();
      {
        String _minLabel_2 = question.getMinLabel();
        boolean _isNullOrEmpty_2 = StringExtensions.isNullOrEmpty(_minLabel_2);
        boolean _not_2 = (!_isNullOrEmpty_2);
        if (_not_2) {
          _builder.append("            \t");
          _builder.append("<td><label for=\"");
          _builder.append(id, "            	");
          _builder.append("_");
          int _min_1 = question.getMin();
          _builder.append(_min_1, "            	");
          _builder.append("\">");
          String _minLabel_3 = question.getMinLabel();
          _builder.append(_minLabel_3, "            	");
          _builder.append("</label></td>");
          _builder.newLineIfNotEmpty();
        }
      }
      {
        int _min_2 = question.getMin();
        int _max_1 = question.getMax();
        IntegerRange _upTo_1 = new IntegerRange(_min_2, _max_1);
        boolean _hasElements_1 = false;
        for(final Integer i_1 : _upTo_1) {
          if (!_hasElements_1) {
            _hasElements_1 = true;
            _builder.append("<td>", "                ");
          } else {
            _builder.appendImmediate("</td><td>", "                ");
          }
          _builder.append("                ");
          _builder.append("<input type=\"radio\" name=\"");
          _builder.append(id, "                ");
          _builder.append("\" id=\"");
          _builder.append(id, "                ");
          _builder.append("_");
          _builder.append(i_1, "                ");
          _builder.append("\" value=\"");
          _builder.append(i_1, "                ");
          _builder.append("\" ");
          CharSequence _genRequiredAttr = this.genRequiredAttr(question, required);
          _builder.append(_genRequiredAttr, "                ");
          _builder.append("/>");
          _builder.newLineIfNotEmpty();
        }
        if (_hasElements_1) {
          _builder.append("</td>", "                ");
        }
      }
      {
        String _minLabel_4 = question.getMinLabel();
        boolean _isNullOrEmpty_3 = StringExtensions.isNullOrEmpty(_minLabel_4);
        boolean _not_3 = (!_isNullOrEmpty_3);
        if (_not_3) {
          _builder.append("            \t");
          _builder.append("<td><label for=\"");
          _builder.append(id, "            	");
          _builder.append("_");
          int _max_2 = question.getMax();
          _builder.append(_max_2, "            	");
          _builder.append("\">");
          String _maxLabel = question.getMaxLabel();
          _builder.append(_maxLabel, "            	");
          _builder.append("</label></td>");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("            ");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  public String genDateFormat(final Date question) {
    ArrayList<String> _arrayList = new ArrayList<String>();
    ArrayList<String> list = _arrayList;
    boolean _isDay = question.isDay();
    if (_isDay) {
      list.add("dd");
    }
    boolean _isMonth = question.isMonth();
    if (_isMonth) {
      list.add("mm");
    }
    boolean _isYear = question.isYear();
    if (_isYear) {
      list.add("yyyy");
    }
    return IterableExtensions.join(list, "/");
  }
  
  public Integer genDateMinViewMode(final Date question) {
    Integer _xblockexpression = null;
    {
      boolean _isDay = question.isDay();
      if (_isDay) {
        return 0;
      }
      boolean _isMonth = question.isMonth();
      if (_isMonth) {
        return 1;
      }
      Integer _xifexpression = null;
      boolean _isYear = question.isYear();
      if (_isYear) {
        return 2;
      }
      _xblockexpression = (_xifexpression);
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final Date question, final boolean required) {
    String _xblockexpression = null;
    {
      final String id = this.getUniqueId(question);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"form-group\">");
      _builder.newLine();
      _builder.append("\t");
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("for=\"");
      _builder_1.append(id, "");
      _builder_1.append("\"");
      CharSequence _genHeader = this.genHeader(question, required, _builder_1.toString());
      _builder.append(_genHeader, "	");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("<div class=\"row\">");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("<div class=\"col-xs-4\">");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("<div class=\"input-group date\"");
      _builder.newLine();
      _builder.append("\t\t    \t");
      _builder.append("data-date-format=\"");
      String _genDateFormat = this.genDateFormat(question);
      _builder.append(_genDateFormat, "		    	");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t    \t");
      _builder.append("data-date-min-view-mode=\"");
      Integer _genDateMinViewMode = this.genDateMinViewMode(question);
      _builder.append(_genDateMinViewMode, "		    	");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t    \t");
      {
        String _start = question.getStart();
        boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_start);
        boolean _not = (!_isNullOrEmpty);
        if (_not) {
          _builder.append("data-date-start-date=\"");
          String _start_1 = question.getStart();
          _builder.append(_start_1, "		    	");
          _builder.append("\"");
        }
      }
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t    \t");
      {
        String _end = question.getEnd();
        boolean _isNullOrEmpty_1 = StringExtensions.isNullOrEmpty(_end);
        boolean _not_1 = (!_isNullOrEmpty_1);
        if (_not_1) {
          _builder.append("data-date-end-date=\"");
          String _end_1 = question.getEnd();
          _builder.append(_end_1, "		    	");
          _builder.append("\"");
        }
      }
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t    \t");
      _builder.append(">");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<input id=\"");
      _builder.append(id, "				");
      _builder.append("\" type=\"text\" class=\"form-control\" ");
      CharSequence _genRequiredAttr = this.genRequiredAttr(question, required);
      _builder.append(_genRequiredAttr, "				");
      _builder.append(">");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t\t");
      _builder.append("<span class=\"input-group-addon\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<i class=\"glyphicon glyphicon-calendar\"></i>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</span>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</div>");
      _builder.newLine();
      {
        boolean _isShowLimits = question.isShowLimits();
        if (_isShowLimits) {
          _builder.append("\t\t");
          CharSequence _genLimitsDesc = this.genLimitsDesc(question);
          _builder.append(_genLimitsDesc, "		");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("    ");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final survey.Number question, final boolean required) {
    String _xblockexpression = null;
    {
      String id = this.getUniqueId(question);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"form-group\">");
      _builder.newLine();
      _builder.append("\t    \t");
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("for=\"");
      _builder_1.append(id, "");
      _builder_1.append("\"");
      CharSequence _genHeader = this.genHeader(question, required, _builder_1.toString());
      _builder.append(_genHeader, "	    	");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("<div class=\"row\">");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("<div class=\"col-xs-2\">");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("<input type=\"number\" class=\"form-control\" id=\"");
      _builder.append(id, "            ");
      _builder.append("\" ");
      CharSequence _genRequiredAttr = this.genRequiredAttr(question, required);
      _builder.append(_genRequiredAttr, "            ");
      _builder.append(" step=\"1\"");
      _builder.newLineIfNotEmpty();
      {
        Integer _min = question.getMin();
        boolean _notEquals = (!Objects.equal(_min, null));
        if (_notEquals) {
          _builder.append("            ");
          _builder.append("min=\"");
          Integer _min_1 = question.getMin();
          _builder.append(_min_1, "            ");
          _builder.append("\"");
          _builder.newLineIfNotEmpty();
        }
      }
      {
        Integer _max = question.getMax();
        boolean _notEquals_1 = (!Objects.equal(_max, null));
        if (_notEquals_1) {
          _builder.append("            ");
          _builder.append("max=\"");
          Integer _max_1 = question.getMax();
          _builder.append(_max_1, "            ");
          _builder.append("\"");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("            ");
      _builder.append(">");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("</div>");
      _builder.newLine();
      {
        boolean _isShowLimits = question.isShowLimits();
        if (_isShowLimits) {
          _builder.append("            ");
          CharSequence _genLimitsDesc = this.genLimitsDesc(question);
          _builder.append(_genLimitsDesc, "            ");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final Single question, final boolean required) {
    String _xblockexpression = null;
    {
      String id = this.getUniqueId(question);
      int i = 0;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"form-group\">");
      _builder.newLine();
      _builder.append("\t    \t");
      CharSequence _genHeader = this.genHeader(question, required);
      _builder.append(_genHeader, "	    	");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("<div>");
      _builder.newLine();
      {
        ArrayList<Answer> _answers = this.getAnswers(question);
        boolean _hasElements = false;
        for(final Answer a : _answers) {
          if (!_hasElements) {
            _hasElements = true;
            _builder.append("<div class=\"radio\"><label>", "		");
          } else {
            _builder.appendImmediate("</label></div><div class=\"radio\"><label>", "		");
          }
          _builder.append("\t\t");
          _builder.append("<input type=\"radio\" name=\"");
          _builder.append(id, "		");
          _builder.append("\" id=\"");
          _builder.append(id, "		");
          _builder.append("_");
          int _plus = (i + 1);
          int _i = i = _plus;
          _builder.append(_i, "		");
          _builder.append("\" value=\"");
          _builder.append(i, "		");
          _builder.append("\" ");
          CharSequence _genRequiredAttr = this.genRequiredAttr(question, required);
          _builder.append(_genRequiredAttr, "		");
          _builder.append("/>");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          String _label = a.getLabel();
          _builder.append(_label, "		");
          _builder.newLineIfNotEmpty();
        }
        if (_hasElements) {
          _builder.append("</label></div>", "		");
        }
      }
      _builder.append("\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final Multiple question, final boolean required) {
    String _xblockexpression = null;
    {
      final String id = this.getUniqueId(question);
      int i = 0;
      final Integer min = this.getMin(question, required);
      final Integer max = this.getMax(question, required);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"form-group\"");
      _builder.newLine();
      _builder.append("\t");
      {
        boolean _greaterThan = ((min).intValue() > 0);
        if (_greaterThan) {
          _builder.append(" data-min-selections=\"");
          _builder.append(min, "	");
          _builder.append("\" ");
        }
      }
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      {
        boolean _notEquals = (!Objects.equal(max, null));
        if (_notEquals) {
          _builder.append(" data-max-selections=\"");
          _builder.append(max, "	");
          _builder.append("\" ");
        }
      }
      _builder.append(">");
      _builder.newLineIfNotEmpty();
      _builder.append("\t    \t");
      CharSequence _genHeader = this.genHeader(question, required);
      _builder.append(_genHeader, "	    	");
      _builder.newLineIfNotEmpty();
      {
        ArrayList<Answer> _answers = this.getAnswers(question);
        boolean _hasElements = false;
        for(final Answer a : _answers) {
          if (!_hasElements) {
            _hasElements = true;
            _builder.append("<div class=\"checkbox\"><label>", "    ");
          } else {
            _builder.appendImmediate("</label></div><div class=\"checkbox\"><label>", "    ");
          }
          _builder.append("    ");
          _builder.append("<input type=\"checkbox\" name=\"");
          _builder.append(id, "    ");
          _builder.append("\" id=\"");
          _builder.append(id, "    ");
          _builder.append("_");
          int _plus = (i + 1);
          int _i = i = _plus;
          _builder.append(_i, "    ");
          _builder.append("\" value=\"");
          _builder.append(i, "    ");
          _builder.append("\"> ");
          String _label = a.getLabel();
          _builder.append(_label, "    ");
          _builder.newLineIfNotEmpty();
        }
        if (_hasElements) {
          _builder.append("</label></div>", "    ");
        }
      }
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final Table question, final boolean required) {
    String _xblockexpression = null;
    {
      final ArrayList<Answer> answers = this.getAnswers(question);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<div class=\"form-group\">");
      _builder.newLine();
      _builder.append("\t    \t");
      CharSequence _genHeader = this.genHeader(question, required);
      _builder.append(_genHeader, "	    	");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("<table class=\"table table-striped\">");
      _builder.newLine();
      _builder.append("    \t");
      _builder.append("<thead>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<th></th>");
      _builder.newLine();
      {
        for(final Answer a : answers) {
          _builder.append("\t\t\t\t");
          _builder.append("<th>");
          String _label = a.getLabel();
          _builder.append(_label, "				");
          _builder.append("</th>");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</thead>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<tbody>");
      _builder.newLine();
      {
        EList<TableQuestion> _questions = question.getQuestions();
        for(final TableQuestion q : _questions) {
          _builder.append("\t\t\t");
          _builder.append("<tr>");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("    ");
          _builder.append("<td><label for=\"");
          String qid = this.getUniqueId(question);
          _builder.append("_");
          int aid = 0;
          _builder.append("\">");
          String _title = q.getTitle();
          _builder.append(_title, "			    ");
          _builder.append("</label></td>");
          _builder.newLineIfNotEmpty();
          {
            for(final Answer a_1 : answers) {
              _builder.append("\t\t\t");
              _builder.append("    ");
              _builder.append("<td><input type=\"");
              {
                boolean _isMultiple = question.isMultiple();
                if (_isMultiple) {
                  _builder.append("checkbox");
                } else {
                  _builder.append("radio");
                }
              }
              _builder.append("\" name=\"");
              _builder.append(qid, "			    ");
              _builder.append("\" id=\"");
              _builder.append(qid, "			    ");
              _builder.append("_");
              int _plus = (aid + 1);
              int _aid = aid = _plus;
              _builder.append(_aid, "			    ");
              _builder.append("\"/></td>");
              _builder.newLineIfNotEmpty();
            }
          }
          _builder.append("\t\t\t");
          _builder.append("</tr>");
          _builder.newLine();
        }
      }
      _builder.append("\t\t");
      _builder.append("</tbody>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("</div>");
      _builder.newLine();
      _xblockexpression = (_builder.toString());
    }
    return _xblockexpression;
  }
  
  protected String _genHtml(final Question question, final boolean required) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("MISSING: ");
    String _title = question.getTitle();
    _builder.append(_title, "");
    _builder.append(" (");
    Class<? extends Question> _class = question.getClass();
    _builder.append(_class, "");
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }
  
  public Integer getMin(final Multiple question, final boolean required) {
    Integer _xifexpression = null;
    Integer _min = question.getMin();
    boolean _notEquals = (!Objects.equal(_min, null));
    if (_notEquals) {
      Integer _min_1 = question.getMin();
      _xifexpression = _min_1;
    } else {
      _xifexpression = Integer.valueOf(0);
    }
    Integer min = _xifexpression;
    boolean _and = false;
    boolean _or = false;
    if (required) {
      _or = true;
    } else {
      boolean _isRequired = question.isRequired();
      _or = (required || _isRequired);
    }
    if (!_or) {
      _and = false;
    } else {
      boolean _equals = ((min).intValue() == 0);
      _and = (_or && _equals);
    }
    if (_and) {
      min = Integer.valueOf(1);
    }
    return min;
  }
  
  public Integer getMax(final Multiple question, final boolean required) {
    Integer _xifexpression = null;
    Integer _max = question.getMax();
    boolean _notEquals = (!Objects.equal(_max, null));
    if (_notEquals) {
      Integer _max_1 = question.getMax();
      int _intValue = _max_1.intValue();
      _xifexpression = Integer.valueOf(_intValue);
    } else {
      _xifexpression = null;
    }
    return _xifexpression;
  }
  
  public CharSequence genRequiredLabel(final Question question, final boolean requiredParent) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _or = false;
      if (requiredParent) {
        _or = true;
      } else {
        boolean _isRequired = question.isRequired();
        _or = (requiredParent || _isRequired);
      }
      if (_or) {
        _builder.append(" * ");
      }
    }
    return _builder;
  }
  
  public CharSequence genRequiredAttr(final Question question, final boolean requiredParent) {
    StringConcatenation _builder = new StringConcatenation();
    {
      boolean _or = false;
      if (requiredParent) {
        _or = true;
      } else {
        boolean _isRequired = question.isRequired();
        _or = (requiredParent || _isRequired);
      }
      if (_or) {
        _builder.append(" required ");
      }
    }
    return _builder;
  }
  
  public CharSequence genLimitsDesc(final Date question) {
    CharSequence _xblockexpression = null;
    {
      final String start = question.getStart();
      final String end = question.getEnd();
      String s = "";
      boolean _and = false;
      boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(start);
      boolean _not = (!_isNullOrEmpty);
      if (!_not) {
        _and = false;
      } else {
        boolean _isNullOrEmpty_1 = StringExtensions.isNullOrEmpty(end);
        boolean _not_1 = (!_isNullOrEmpty_1);
        _and = (_not && _not_1);
      }
      if (_and) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("The date must be between ");
        _builder.append(start, "");
        _builder.append(" and ");
        _builder.append(end, "");
        s = _builder.toString();
      } else {
        boolean _isNullOrEmpty_2 = StringExtensions.isNullOrEmpty(start);
        boolean _not_2 = (!_isNullOrEmpty_2);
        if (_not_2) {
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("The date must be before ");
          _builder_1.append(end, "");
          s = _builder_1.toString();
        } else {
          boolean _isNullOrEmpty_3 = StringExtensions.isNullOrEmpty(end);
          boolean _not_3 = (!_isNullOrEmpty_3);
          if (_not_3) {
            StringConcatenation _builder_2 = new StringConcatenation();
            _builder_2.append("The date must be after ");
            _builder_2.append(start, "");
            s = _builder_2.toString();
          }
        }
      }
      CharSequence _xifexpression = null;
      boolean _isNullOrEmpty_4 = StringExtensions.isNullOrEmpty(s);
      boolean _not_4 = (!_isNullOrEmpty_4);
      if (_not_4) {
        StringConcatenation _builder_3 = new StringConcatenation();
        _builder_3.append("<p class=\"help-block\">");
        _builder_3.append(s, "");
        _builder_3.append("</p>");
        _xifexpression = _builder_3;
      }
      _xblockexpression = (_xifexpression);
    }
    return _xblockexpression;
  }
  
  public CharSequence genLimitsDesc(final survey.Number question) {
    CharSequence _xblockexpression = null;
    {
      final Integer min = question.getMin();
      final Integer max = question.getMax();
      String s = "";
      boolean _and = false;
      boolean _notEquals = (!Objects.equal(min, null));
      if (!_notEquals) {
        _and = false;
      } else {
        boolean _notEquals_1 = (!Objects.equal(max, null));
        _and = (_notEquals && _notEquals_1);
      }
      if (_and) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("The value must be between ");
        _builder.append(min, "");
        _builder.append(" and ");
        _builder.append(max, "");
        _builder.append(" (both included)");
        s = _builder.toString();
      } else {
        boolean _notEquals_2 = (!Objects.equal(min, null));
        if (_notEquals_2) {
          boolean _matched = false;
          if (!_matched) {
            if (Objects.equal(min,0)) {
              _matched=true;
              StringConcatenation _builder_1 = new StringConcatenation();
              _builder_1.append("The value must be non-negative");
              s = _builder_1.toString();
            }
          }
          if (!_matched) {
            if (Objects.equal(min,1)) {
              _matched=true;
              StringConcatenation _builder_2 = new StringConcatenation();
              _builder_2.append("The value must be positive");
              s = _builder_2.toString();
            }
          }
          if (!_matched) {
            StringConcatenation _builder_3 = new StringConcatenation();
            _builder_3.append("The value must be larger than or equal to ");
            _builder_3.append(min, "");
            s = _builder_3.toString();
          }
        } else {
          boolean _notEquals_3 = (!Objects.equal(max, null));
          if (_notEquals_3) {
            boolean _matched_1 = false;
            if (!_matched_1) {
              int _minus = (-1);
              if (Objects.equal(max,_minus)) {
                _matched_1=true;
                StringConcatenation _builder_4 = new StringConcatenation();
                _builder_4.append("The value must be negative");
                s = _builder_4.toString();
              }
            }
            if (!_matched_1) {
              StringConcatenation _builder_5 = new StringConcatenation();
              _builder_5.append("The value must be less than or equal to ");
              _builder_5.append(max, "");
              s = _builder_5.toString();
            }
          }
        }
      }
      CharSequence _xifexpression = null;
      boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(s);
      boolean _not = (!_isNullOrEmpty);
      if (_not) {
        StringConcatenation _builder_6 = new StringConcatenation();
        _builder_6.append("<p class=\"help-block\">");
        _builder_6.append(s, "");
        _builder_6.append("</p>");
        _xifexpression = _builder_6;
      }
      _xblockexpression = (_xifexpression);
    }
    return _xblockexpression;
  }
  
  public ArrayList<Answer> getAnswers(final HasOptions hasOptions) {
    ArrayList<Answer> _arrayList = new ArrayList<Answer>();
    ArrayList<Answer> answers = _arrayList;
    EList<Option> _options = hasOptions.getOptions();
    for (final Option option : _options) {
      if ((option instanceof Answer)) {
        answers.add(((Answer) option));
      } else {
        if ((option instanceof AnswerTemplateRef)) {
          AnswerTemplate _template = ((AnswerTemplateRef) option).getTemplate();
          EList<Answer> _answers = _template.getAnswers();
          answers.addAll(_answers);
        }
      }
    }
    return answers;
  }
  
  public void genLatex(final Survey survey, final IFileSystemAccess fsa) {
    fsa.generateFile("survey.tex", "Something something");
  }
  
  public String genHtml(final Item question, final boolean required) {
    if (question instanceof Date) {
      return _genHtml((Date)question, required);
    } else if (question instanceof Multiple) {
      return _genHtml((Multiple)question, required);
    } else if (question instanceof survey.Number) {
      return _genHtml((survey.Number)question, required);
    } else if (question instanceof Scale) {
      return _genHtml((Scale)question, required);
    } else if (question instanceof Single) {
      return _genHtml((Single)question, required);
    } else if (question instanceof Table) {
      return _genHtml((Table)question, required);
    } else if (question instanceof Text) {
      return _genHtml((Text)question, required);
    } else if (question instanceof Group) {
      return _genHtml((Group)question, required);
    } else if (question instanceof Question) {
      return _genHtml((Question)question, required);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(question, required).toString());
    }
  }
}
