/*
* generated by Xtext
*/
package dk.itu.smdp.survey.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SurveyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Survey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSurveyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSurveyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_3_1_0 = (RuleCall)cTitleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cItemsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cItemsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cItemsItemParserRuleCall_5_2_0 = (RuleCall)cItemsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cItemsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cItemsItemParserRuleCall_5_3_1_0 = (RuleCall)cItemsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTemplatesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTemplatesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTemplatesAnswerTemplateParserRuleCall_6_2_0 = (RuleCall)cTemplatesAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cTemplatesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cTemplatesAnswerTemplateParserRuleCall_6_3_1_0 = (RuleCall)cTemplatesAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Survey:
		//	{Survey} "Survey" "{" ("title" title=EString)? ("description" description=EString)? ("items" "{" items+=Item (","
		//	items+=Item)* "}")? ("templates" "{" templates+=AnswerTemplate ("," templates+=AnswerTemplate)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Survey} "Survey" "{" ("title" title=EString)? ("description" description=EString)? ("items" "{" items+=Item (","
		//items+=Item)* "}")? ("templates" "{" templates+=AnswerTemplate ("," templates+=AnswerTemplate)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Survey}
		public Action getSurveyAction_0() { return cSurveyAction_0; }

		//"Survey"
		public Keyword getSurveyKeyword_1() { return cSurveyKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("title" title=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"title"
		public Keyword getTitleKeyword_3_0() { return cTitleKeyword_3_0; }

		//title=EString
		public Assignment getTitleAssignment_3_1() { return cTitleAssignment_3_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_3_1_0() { return cTitleEStringParserRuleCall_3_1_0; }

		//("description" description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//("items" "{" items+=Item ("," items+=Item)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"items"
		public Keyword getItemsKeyword_5_0() { return cItemsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//items+=Item
		public Assignment getItemsAssignment_5_2() { return cItemsAssignment_5_2; }

		//Item
		public RuleCall getItemsItemParserRuleCall_5_2_0() { return cItemsItemParserRuleCall_5_2_0; }

		//("," items+=Item)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//items+=Item
		public Assignment getItemsAssignment_5_3_1() { return cItemsAssignment_5_3_1; }

		//Item
		public RuleCall getItemsItemParserRuleCall_5_3_1_0() { return cItemsItemParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("templates" "{" templates+=AnswerTemplate ("," templates+=AnswerTemplate)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"templates"
		public Keyword getTemplatesKeyword_6_0() { return cTemplatesKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//templates+=AnswerTemplate
		public Assignment getTemplatesAssignment_6_2() { return cTemplatesAssignment_6_2; }

		//AnswerTemplate
		public RuleCall getTemplatesAnswerTemplateParserRuleCall_6_2_0() { return cTemplatesAnswerTemplateParserRuleCall_6_2_0; }

		//("," templates+=AnswerTemplate)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//templates+=AnswerTemplate
		public Assignment getTemplatesAssignment_6_3_1() { return cTemplatesAssignment_6_3_1; }

		//AnswerTemplate
		public RuleCall getTemplatesAnswerTemplateParserRuleCall_6_3_1_0() { return cTemplatesAnswerTemplateParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Item");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGroupParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSingleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMultipleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTextParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDateParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cNumberParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cScaleParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cTableParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Item:
		//	Group | Single | Multiple | Text | Date | Number | Scale | Table;
		public ParserRule getRule() { return rule; }

		//Group | Single | Multiple | Text | Date | Number | Scale | Table
		public Alternatives getAlternatives() { return cAlternatives; }

		//Group
		public RuleCall getGroupParserRuleCall_0() { return cGroupParserRuleCall_0; }

		//Single
		public RuleCall getSingleParserRuleCall_1() { return cSingleParserRuleCall_1; }

		//Multiple
		public RuleCall getMultipleParserRuleCall_2() { return cMultipleParserRuleCall_2; }

		//Text
		public RuleCall getTextParserRuleCall_3() { return cTextParserRuleCall_3; }

		//Date
		public RuleCall getDateParserRuleCall_4() { return cDateParserRuleCall_4; }

		//Number
		public RuleCall getNumberParserRuleCall_5() { return cNumberParserRuleCall_5; }

		//Scale
		public RuleCall getScaleParserRuleCall_6() { return cScaleParserRuleCall_6; }

		//Table
		public RuleCall getTableParserRuleCall_7() { return cTableParserRuleCall_7; }
	}

	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSingleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMultipleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDateParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cNumberParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cScaleParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cTableParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Question:
		//	Single | Multiple | Text | Date | Number | Scale | Table;
		public ParserRule getRule() { return rule; }

		//Single | Multiple | Text | Date | Number | Scale | Table
		public Alternatives getAlternatives() { return cAlternatives; }

		//Single
		public RuleCall getSingleParserRuleCall_0() { return cSingleParserRuleCall_0; }

		//Multiple
		public RuleCall getMultipleParserRuleCall_1() { return cMultipleParserRuleCall_1; }

		//Text
		public RuleCall getTextParserRuleCall_2() { return cTextParserRuleCall_2; }

		//Date
		public RuleCall getDateParserRuleCall_3() { return cDateParserRuleCall_3; }

		//Number
		public RuleCall getNumberParserRuleCall_4() { return cNumberParserRuleCall_4; }

		//Scale
		public RuleCall getScaleParserRuleCall_5() { return cScaleParserRuleCall_5; }

		//Table
		public RuleCall getTableParserRuleCall_6() { return cTableParserRuleCall_6; }
	}

	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Option");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOption_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAnswerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAnswerTemplateParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Option:
		//	Option_Impl | Answer | AnswerTemplate;
		public ParserRule getRule() { return rule; }

		//Option_Impl | Answer | AnswerTemplate
		public Alternatives getAlternatives() { return cAlternatives; }

		//Option_Impl
		public RuleCall getOption_ImplParserRuleCall_0() { return cOption_ImplParserRuleCall_0; }

		//Answer
		public RuleCall getAnswerParserRuleCall_1() { return cAnswerParserRuleCall_1; }

		//AnswerTemplate
		public RuleCall getAnswerTemplateParserRuleCall_2() { return cAnswerTemplateParserRuleCall_2; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class AnswerTemplateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnswerTemplate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnswerTemplateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIdAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdEStringParserRuleCall_3_0 = (RuleCall)cIdAssignment_3.eContents().get(0);
		private final Keyword cAnswersKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAnswersAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAnswersAnswerParserRuleCall_6_0 = (RuleCall)cAnswersAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAnswersAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAnswersAnswerParserRuleCall_7_1_0 = (RuleCall)cAnswersAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//AnswerTemplate:
		//	"AnswerTemplate" "{" "id" id=EString "answers" "{" answers+=Answer ("," answers+=Answer)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"AnswerTemplate" "{" "id" id=EString "answers" "{" answers+=Answer ("," answers+=Answer)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"AnswerTemplate"
		public Keyword getAnswerTemplateKeyword_0() { return cAnswerTemplateKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"id"
		public Keyword getIdKeyword_2() { return cIdKeyword_2; }

		//id=EString
		public Assignment getIdAssignment_3() { return cIdAssignment_3; }

		//EString
		public RuleCall getIdEStringParserRuleCall_3_0() { return cIdEStringParserRuleCall_3_0; }

		//"answers"
		public Keyword getAnswersKeyword_4() { return cAnswersKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//answers+=Answer
		public Assignment getAnswersAssignment_6() { return cAnswersAssignment_6; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_6_0() { return cAnswersAnswerParserRuleCall_6_0; }

		//("," answers+=Answer)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//answers+=Answer
		public Assignment getAnswersAssignment_7_1() { return cAnswersAssignment_7_1; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_7_1_0() { return cAnswersAnswerParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class AnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Answer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnswerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Keyword cLabelKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLabelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLabelEStringParserRuleCall_4_0 = (RuleCall)cLabelAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Answer:
		//	"Answer" "{" ("id" id=EString)? "label" label=EString "}";
		public ParserRule getRule() { return rule; }

		//"Answer" "{" ("id" id=EString)? "label" label=EString "}"
		public Group getGroup() { return cGroup; }

		//"Answer"
		public Keyword getAnswerKeyword_0() { return cAnswerKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("id" id=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"id"
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }

		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }

		//"label"
		public Keyword getLabelKeyword_3() { return cLabelKeyword_3; }

		//label=EString
		public Assignment getLabelAssignment_4() { return cLabelAssignment_4; }

		//EString
		public RuleCall getLabelEStringParserRuleCall_4_0() { return cLabelEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRequiredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRequiredRequiredKeyword_0_0 = (Keyword)cRequiredAssignment_0.eContents().get(0);
		private final Keyword cGroupKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_3_1_0 = (RuleCall)cTitleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDependsOnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDependsOnAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_5_1_0 = (CrossReference)cDependsOnAssignment_5_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_5_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_5_1_0.eContents().get(1);
		private final Keyword cQuestionsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cQuestionsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cQuestionsQuestionParserRuleCall_8_0 = (RuleCall)cQuestionsAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cQuestionsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cQuestionsQuestionParserRuleCall_9_1_0 = (RuleCall)cQuestionsAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Group:
		//	required?="required"? "Group" "{" ("title" title=EString)? ("description" description=EString)? ("dependsOn"
		//	dependsOn=[Answer|EString])? "questions" "{" questions+=Question ("," questions+=Question)* "}" "}";
		public ParserRule getRule() { return rule; }

		//required?="required"? "Group" "{" ("title" title=EString)? ("description" description=EString)? ("dependsOn"
		//dependsOn=[Answer|EString])? "questions" "{" questions+=Question ("," questions+=Question)* "}" "}"
		public Group getGroup() { return cGroup; }

		//required?="required"?
		public Assignment getRequiredAssignment_0() { return cRequiredAssignment_0; }

		//"required"
		public Keyword getRequiredRequiredKeyword_0_0() { return cRequiredRequiredKeyword_0_0; }

		//"Group"
		public Keyword getGroupKeyword_1() { return cGroupKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("title" title=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"title"
		public Keyword getTitleKeyword_3_0() { return cTitleKeyword_3_0; }

		//title=EString
		public Assignment getTitleAssignment_3_1() { return cTitleAssignment_3_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_3_1_0() { return cTitleEStringParserRuleCall_3_1_0; }

		//("description" description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_5() { return cGroup_5; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_5_0() { return cDependsOnKeyword_5_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_5_1() { return cDependsOnAssignment_5_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_5_1_0() { return cDependsOnAnswerCrossReference_5_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_5_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_5_1_0_1; }

		//"questions"
		public Keyword getQuestionsKeyword_6() { return cQuestionsKeyword_6; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }

		//questions+=Question
		public Assignment getQuestionsAssignment_8() { return cQuestionsAssignment_8; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_8_0() { return cQuestionsQuestionParserRuleCall_8_0; }

		//("," questions+=Question)*
		public Group getGroup_9() { return cGroup_9; }

		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }

		//questions+=Question
		public Assignment getQuestionsAssignment_9_1() { return cQuestionsAssignment_9_1; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_9_1_0() { return cQuestionsQuestionParserRuleCall_9_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class SingleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Single");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRequiredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRequiredRequiredKeyword_0_0 = (Keyword)cRequiredAssignment_0.eContents().get(0);
		private final Assignment cOtherAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOtherOtherKeyword_1_0 = (Keyword)cOtherAssignment_1.eContents().get(0);
		private final Keyword cSingleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIdAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_6_1_0 = (RuleCall)cIdAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDependsOnKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDependsOnAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_7_1_0 = (CrossReference)cDependsOnAssignment_7_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_7_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTemplateKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTemplateAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cTemplateOptionCrossReference_8_1_0 = (CrossReference)cTemplateAssignment_8_1.eContents().get(0);
		private final RuleCall cTemplateOptionEStringParserRuleCall_8_1_0_1 = (RuleCall)cTemplateOptionCrossReference_8_1_0.eContents().get(1);
		private final Keyword cOptionsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cOptionsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cOptionsOptionParserRuleCall_11_0 = (RuleCall)cOptionsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cOptionsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cOptionsOptionParserRuleCall_12_1_0 = (RuleCall)cOptionsAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Single:
		//	required?="required"? other?="other"? "Single" "{" ("title" title=EString)? ("description" description=EString)? ("id"
		//	id=EString)? ("dependsOn" dependsOn=[Answer|EString])? ("template" template=[Option|EString])? "options" "{"
		//	options+=Option ("," options+=Option)* "}" "}";
		public ParserRule getRule() { return rule; }

		//required?="required"? other?="other"? "Single" "{" ("title" title=EString)? ("description" description=EString)? ("id"
		//id=EString)? ("dependsOn" dependsOn=[Answer|EString])? ("template" template=[Option|EString])? "options" "{"
		//options+=Option ("," options+=Option)* "}" "}"
		public Group getGroup() { return cGroup; }

		//required?="required"?
		public Assignment getRequiredAssignment_0() { return cRequiredAssignment_0; }

		//"required"
		public Keyword getRequiredRequiredKeyword_0_0() { return cRequiredRequiredKeyword_0_0; }

		//other?="other"?
		public Assignment getOtherAssignment_1() { return cOtherAssignment_1; }

		//"other"
		public Keyword getOtherOtherKeyword_1_0() { return cOtherOtherKeyword_1_0; }

		//"Single"
		public Keyword getSingleKeyword_2() { return cSingleKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("title" title=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"title"
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }

		//title=EString
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_4_1_0() { return cTitleEStringParserRuleCall_4_1_0; }

		//("description" description=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"description"
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }

		//description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }

		//("id" id=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"id"
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }

		//id=EString
		public Assignment getIdAssignment_6_1() { return cIdAssignment_6_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_6_1_0() { return cIdEStringParserRuleCall_6_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_7() { return cGroup_7; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_7_0() { return cDependsOnKeyword_7_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_7_1() { return cDependsOnAssignment_7_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_7_1_0() { return cDependsOnAnswerCrossReference_7_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_7_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_7_1_0_1; }

		//("template" template=[Option|EString])?
		public Group getGroup_8() { return cGroup_8; }

		//"template"
		public Keyword getTemplateKeyword_8_0() { return cTemplateKeyword_8_0; }

		//template=[Option|EString]
		public Assignment getTemplateAssignment_8_1() { return cTemplateAssignment_8_1; }

		//[Option|EString]
		public CrossReference getTemplateOptionCrossReference_8_1_0() { return cTemplateOptionCrossReference_8_1_0; }

		//EString
		public RuleCall getTemplateOptionEStringParserRuleCall_8_1_0_1() { return cTemplateOptionEStringParserRuleCall_8_1_0_1; }

		//"options"
		public Keyword getOptionsKeyword_9() { return cOptionsKeyword_9; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }

		//options+=Option
		public Assignment getOptionsAssignment_11() { return cOptionsAssignment_11; }

		//Option
		public RuleCall getOptionsOptionParserRuleCall_11_0() { return cOptionsOptionParserRuleCall_11_0; }

		//("," options+=Option)*
		public Group getGroup_12() { return cGroup_12; }

		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }

		//options+=Option
		public Assignment getOptionsAssignment_12_1() { return cOptionsAssignment_12_1; }

		//Option
		public RuleCall getOptionsOptionParserRuleCall_12_1_0() { return cOptionsOptionParserRuleCall_12_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class MultipleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Multiple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRequiredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRequiredRequiredKeyword_0_0 = (Keyword)cRequiredAssignment_0.eContents().get(0);
		private final Assignment cOtherAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOtherOtherKeyword_1_0 = (Keyword)cOtherAssignment_1.eContents().get(0);
		private final Assignment cShowLimitsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cShowLimitsShowLimitsKeyword_2_0 = (Keyword)cShowLimitsAssignment_2.eContents().get(0);
		private final Keyword cMultipleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIdKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIdAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_7_1_0 = (RuleCall)cIdAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLowerKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cLowerAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cLowerEIntParserRuleCall_8_1_0 = (RuleCall)cLowerAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cUpperKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cUpperAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cUpperEIntParserRuleCall_9_1_0 = (RuleCall)cUpperAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cDependsOnKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cDependsOnAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_10_1_0 = (CrossReference)cDependsOnAssignment_10_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_10_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cTemplateKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cTemplateAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cTemplateOptionCrossReference_11_1_0 = (CrossReference)cTemplateAssignment_11_1.eContents().get(0);
		private final RuleCall cTemplateOptionEStringParserRuleCall_11_1_0_1 = (RuleCall)cTemplateOptionCrossReference_11_1_0.eContents().get(1);
		private final Keyword cOptionsKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cOptionsAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cOptionsOptionParserRuleCall_14_0 = (RuleCall)cOptionsAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cOptionsAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cOptionsOptionParserRuleCall_15_1_0 = (RuleCall)cOptionsAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//Multiple:
		//	required?="required"? other?="other"? showLimits?="showLimits"? "Multiple" "{" ("title" title=EString)? ("description"
		//	description=EString)? ("id" id=EString)? ("lower" lower=EInt)? ("upper" upper=EInt)? ("dependsOn"
		//	dependsOn=[Answer|EString])? ("template" template=[Option|EString])? "options" "{" options+=Option (","
		//	options+=Option)* "}" "}";
		public ParserRule getRule() { return rule; }

		//required?="required"? other?="other"? showLimits?="showLimits"? "Multiple" "{" ("title" title=EString)? ("description"
		//description=EString)? ("id" id=EString)? ("lower" lower=EInt)? ("upper" upper=EInt)? ("dependsOn"
		//dependsOn=[Answer|EString])? ("template" template=[Option|EString])? "options" "{" options+=Option (","
		//options+=Option)* "}" "}"
		public Group getGroup() { return cGroup; }

		//required?="required"?
		public Assignment getRequiredAssignment_0() { return cRequiredAssignment_0; }

		//"required"
		public Keyword getRequiredRequiredKeyword_0_0() { return cRequiredRequiredKeyword_0_0; }

		//other?="other"?
		public Assignment getOtherAssignment_1() { return cOtherAssignment_1; }

		//"other"
		public Keyword getOtherOtherKeyword_1_0() { return cOtherOtherKeyword_1_0; }

		//showLimits?="showLimits"?
		public Assignment getShowLimitsAssignment_2() { return cShowLimitsAssignment_2; }

		//"showLimits"
		public Keyword getShowLimitsShowLimitsKeyword_2_0() { return cShowLimitsShowLimitsKeyword_2_0; }

		//"Multiple"
		public Keyword getMultipleKeyword_3() { return cMultipleKeyword_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("description" description=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"description"
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }

		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }

		//("id" id=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"id"
		public Keyword getIdKeyword_7_0() { return cIdKeyword_7_0; }

		//id=EString
		public Assignment getIdAssignment_7_1() { return cIdAssignment_7_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_7_1_0() { return cIdEStringParserRuleCall_7_1_0; }

		//("lower" lower=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"lower"
		public Keyword getLowerKeyword_8_0() { return cLowerKeyword_8_0; }

		//lower=EInt
		public Assignment getLowerAssignment_8_1() { return cLowerAssignment_8_1; }

		//EInt
		public RuleCall getLowerEIntParserRuleCall_8_1_0() { return cLowerEIntParserRuleCall_8_1_0; }

		//("upper" upper=EInt)?
		public Group getGroup_9() { return cGroup_9; }

		//"upper"
		public Keyword getUpperKeyword_9_0() { return cUpperKeyword_9_0; }

		//upper=EInt
		public Assignment getUpperAssignment_9_1() { return cUpperAssignment_9_1; }

		//EInt
		public RuleCall getUpperEIntParserRuleCall_9_1_0() { return cUpperEIntParserRuleCall_9_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_10() { return cGroup_10; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_10_0() { return cDependsOnKeyword_10_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_10_1() { return cDependsOnAssignment_10_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_10_1_0() { return cDependsOnAnswerCrossReference_10_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_10_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_10_1_0_1; }

		//("template" template=[Option|EString])?
		public Group getGroup_11() { return cGroup_11; }

		//"template"
		public Keyword getTemplateKeyword_11_0() { return cTemplateKeyword_11_0; }

		//template=[Option|EString]
		public Assignment getTemplateAssignment_11_1() { return cTemplateAssignment_11_1; }

		//[Option|EString]
		public CrossReference getTemplateOptionCrossReference_11_1_0() { return cTemplateOptionCrossReference_11_1_0; }

		//EString
		public RuleCall getTemplateOptionEStringParserRuleCall_11_1_0_1() { return cTemplateOptionEStringParserRuleCall_11_1_0_1; }

		//"options"
		public Keyword getOptionsKeyword_12() { return cOptionsKeyword_12; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }

		//options+=Option
		public Assignment getOptionsAssignment_14() { return cOptionsAssignment_14; }

		//Option
		public RuleCall getOptionsOptionParserRuleCall_14_0() { return cOptionsOptionParserRuleCall_14_0; }

		//("," options+=Option)*
		public Group getGroup_15() { return cGroup_15; }

		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }

		//options+=Option
		public Assignment getOptionsAssignment_15_1() { return cOptionsAssignment_15_1; }

		//Option
		public RuleCall getOptionsOptionParserRuleCall_15_1_0() { return cOptionsOptionParserRuleCall_15_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}

	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Text");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTextAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cRequiredAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cRequiredRequiredKeyword_1_0 = (Keyword)cRequiredAssignment_1.eContents().get(0);
		private final Assignment cMultilineAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cMultilineMultilineKeyword_2_0 = (Keyword)cMultilineAssignment_2.eContents().get(0);
		private final Keyword cTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIdKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIdAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_7_1_0 = (RuleCall)cIdAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDependsOnKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDependsOnAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_8_1_0 = (CrossReference)cDependsOnAssignment_8_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_8_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Text:
		//	{Text} required?="required"? multiline?="multiline"? "Text" "{" ("title" title=EString)? ("description"
		//	description=EString)? ("id" id=EString)? ("dependsOn" dependsOn=[Answer|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Text} required?="required"? multiline?="multiline"? "Text" "{" ("title" title=EString)? ("description"
		//description=EString)? ("id" id=EString)? ("dependsOn" dependsOn=[Answer|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Text}
		public Action getTextAction_0() { return cTextAction_0; }

		//required?="required"?
		public Assignment getRequiredAssignment_1() { return cRequiredAssignment_1; }

		//"required"
		public Keyword getRequiredRequiredKeyword_1_0() { return cRequiredRequiredKeyword_1_0; }

		//multiline?="multiline"?
		public Assignment getMultilineAssignment_2() { return cMultilineAssignment_2; }

		//"multiline"
		public Keyword getMultilineMultilineKeyword_2_0() { return cMultilineMultilineKeyword_2_0; }

		//"Text"
		public Keyword getTextKeyword_3() { return cTextKeyword_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("description" description=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"description"
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }

		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }

		//("id" id=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"id"
		public Keyword getIdKeyword_7_0() { return cIdKeyword_7_0; }

		//id=EString
		public Assignment getIdAssignment_7_1() { return cIdAssignment_7_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_7_1_0() { return cIdEStringParserRuleCall_7_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_8() { return cGroup_8; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_8_0() { return cDependsOnKeyword_8_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_8_1() { return cDependsOnAssignment_8_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_8_1_0() { return cDependsOnAnswerCrossReference_8_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_8_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_8_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDateAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cRequiredAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cRequiredRequiredKeyword_1_0 = (Keyword)cRequiredAssignment_1.eContents().get(0);
		private final Assignment cDayAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cDayDayKeyword_2_0 = (Keyword)cDayAssignment_2.eContents().get(0);
		private final Assignment cMonthAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cMonthMonthKeyword_3_0 = (Keyword)cMonthAssignment_3.eContents().get(0);
		private final Assignment cYearAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cYearYearKeyword_4_0 = (Keyword)cYearAssignment_4.eContents().get(0);
		private final Keyword cDateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTitleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTitleAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_7_1_0 = (RuleCall)cTitleAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDescriptionKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDescriptionAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_8_1_0 = (RuleCall)cDescriptionAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cIdKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cIdAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_9_1_0 = (RuleCall)cIdAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cFromKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cFromAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cFromEStringParserRuleCall_10_1_0 = (RuleCall)cFromAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cToKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cToAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cToEStringParserRuleCall_11_1_0 = (RuleCall)cToAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cDependsOnKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cDependsOnAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_12_1_0 = (CrossReference)cDependsOnAssignment_12_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_12_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_12_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Date:
		//	{Date} required?="required"? day?="day"? month?="month"? year?="year"? "Date" "{" ("title" title=EString)?
		//	("description" description=EString)? ("id" id=EString)? ("from" from=EString)? ("to" to=EString)? ("dependsOn"
		//	dependsOn=[Answer|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Date} required?="required"? day?="day"? month?="month"? year?="year"? "Date" "{" ("title" title=EString)?
		//("description" description=EString)? ("id" id=EString)? ("from" from=EString)? ("to" to=EString)? ("dependsOn"
		//dependsOn=[Answer|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Date}
		public Action getDateAction_0() { return cDateAction_0; }

		//required?="required"?
		public Assignment getRequiredAssignment_1() { return cRequiredAssignment_1; }

		//"required"
		public Keyword getRequiredRequiredKeyword_1_0() { return cRequiredRequiredKeyword_1_0; }

		//day?="day"?
		public Assignment getDayAssignment_2() { return cDayAssignment_2; }

		//"day"
		public Keyword getDayDayKeyword_2_0() { return cDayDayKeyword_2_0; }

		//month?="month"?
		public Assignment getMonthAssignment_3() { return cMonthAssignment_3; }

		//"month"
		public Keyword getMonthMonthKeyword_3_0() { return cMonthMonthKeyword_3_0; }

		//year?="year"?
		public Assignment getYearAssignment_4() { return cYearAssignment_4; }

		//"year"
		public Keyword getYearYearKeyword_4_0() { return cYearYearKeyword_4_0; }

		//"Date"
		public Keyword getDateKeyword_5() { return cDateKeyword_5; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }

		//("title" title=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"title"
		public Keyword getTitleKeyword_7_0() { return cTitleKeyword_7_0; }

		//title=EString
		public Assignment getTitleAssignment_7_1() { return cTitleAssignment_7_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_7_1_0() { return cTitleEStringParserRuleCall_7_1_0; }

		//("description" description=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"description"
		public Keyword getDescriptionKeyword_8_0() { return cDescriptionKeyword_8_0; }

		//description=EString
		public Assignment getDescriptionAssignment_8_1() { return cDescriptionAssignment_8_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_8_1_0() { return cDescriptionEStringParserRuleCall_8_1_0; }

		//("id" id=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"id"
		public Keyword getIdKeyword_9_0() { return cIdKeyword_9_0; }

		//id=EString
		public Assignment getIdAssignment_9_1() { return cIdAssignment_9_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_9_1_0() { return cIdEStringParserRuleCall_9_1_0; }

		//("from" from=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"from"
		public Keyword getFromKeyword_10_0() { return cFromKeyword_10_0; }

		//from=EString
		public Assignment getFromAssignment_10_1() { return cFromAssignment_10_1; }

		//EString
		public RuleCall getFromEStringParserRuleCall_10_1_0() { return cFromEStringParserRuleCall_10_1_0; }

		//("to" to=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"to"
		public Keyword getToKeyword_11_0() { return cToKeyword_11_0; }

		//to=EString
		public Assignment getToAssignment_11_1() { return cToAssignment_11_1; }

		//EString
		public RuleCall getToEStringParserRuleCall_11_1_0() { return cToEStringParserRuleCall_11_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_12() { return cGroup_12; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_12_0() { return cDependsOnKeyword_12_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_12_1() { return cDependsOnAssignment_12_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_12_1_0() { return cDependsOnAnswerCrossReference_12_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_12_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_12_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Number");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumberAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cRequiredAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cRequiredRequiredKeyword_1_0 = (Keyword)cRequiredAssignment_1.eContents().get(0);
		private final Assignment cShowLimitsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cShowLimitsShowLimitsKeyword_2_0 = (Keyword)cShowLimitsAssignment_2.eContents().get(0);
		private final Keyword cNumberKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIdKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIdAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_7_1_0 = (RuleCall)cIdAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLowerKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cLowerAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cLowerEIntParserRuleCall_8_1_0 = (RuleCall)cLowerAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cUpperKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cUpperAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cUpperEIntParserRuleCall_9_1_0 = (RuleCall)cUpperAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cDependsOnKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cDependsOnAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_10_1_0 = (CrossReference)cDependsOnAssignment_10_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_10_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Number:
		//	{Number} required?="required"? showLimits?="showLimits"? "Number" "{" ("title" title=EString)? ("description"
		//	description=EString)? ("id" id=EString)? ("lower" lower=EInt)? ("upper" upper=EInt)? ("dependsOn"
		//	dependsOn=[Answer|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Number} required?="required"? showLimits?="showLimits"? "Number" "{" ("title" title=EString)? ("description"
		//description=EString)? ("id" id=EString)? ("lower" lower=EInt)? ("upper" upper=EInt)? ("dependsOn"
		//dependsOn=[Answer|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Number}
		public Action getNumberAction_0() { return cNumberAction_0; }

		//required?="required"?
		public Assignment getRequiredAssignment_1() { return cRequiredAssignment_1; }

		//"required"
		public Keyword getRequiredRequiredKeyword_1_0() { return cRequiredRequiredKeyword_1_0; }

		//showLimits?="showLimits"?
		public Assignment getShowLimitsAssignment_2() { return cShowLimitsAssignment_2; }

		//"showLimits"
		public Keyword getShowLimitsShowLimitsKeyword_2_0() { return cShowLimitsShowLimitsKeyword_2_0; }

		//"Number"
		public Keyword getNumberKeyword_3() { return cNumberKeyword_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("description" description=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"description"
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }

		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }

		//("id" id=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"id"
		public Keyword getIdKeyword_7_0() { return cIdKeyword_7_0; }

		//id=EString
		public Assignment getIdAssignment_7_1() { return cIdAssignment_7_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_7_1_0() { return cIdEStringParserRuleCall_7_1_0; }

		//("lower" lower=EInt)?
		public Group getGroup_8() { return cGroup_8; }

		//"lower"
		public Keyword getLowerKeyword_8_0() { return cLowerKeyword_8_0; }

		//lower=EInt
		public Assignment getLowerAssignment_8_1() { return cLowerAssignment_8_1; }

		//EInt
		public RuleCall getLowerEIntParserRuleCall_8_1_0() { return cLowerEIntParserRuleCall_8_1_0; }

		//("upper" upper=EInt)?
		public Group getGroup_9() { return cGroup_9; }

		//"upper"
		public Keyword getUpperKeyword_9_0() { return cUpperKeyword_9_0; }

		//upper=EInt
		public Assignment getUpperAssignment_9_1() { return cUpperAssignment_9_1; }

		//EInt
		public RuleCall getUpperEIntParserRuleCall_9_1_0() { return cUpperEIntParserRuleCall_9_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_10() { return cGroup_10; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_10_0() { return cDependsOnKeyword_10_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_10_1() { return cDependsOnAssignment_10_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_10_1_0() { return cDependsOnAnswerCrossReference_10_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_10_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_10_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class ScaleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Scale");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRequiredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRequiredRequiredKeyword_0_0 = (Keyword)cRequiredAssignment_0.eContents().get(0);
		private final Keyword cScaleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_3_1_0 = (RuleCall)cTitleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_5_1_0 = (RuleCall)cIdAssignment_5_1.eContents().get(0);
		private final Keyword cLowerKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLowerAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLowerEIntParserRuleCall_7_0 = (RuleCall)cLowerAssignment_7.eContents().get(0);
		private final Keyword cUpperKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cUpperAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cUpperEIntParserRuleCall_9_0 = (RuleCall)cUpperAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cLowerLabelKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cLowerLabelAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cLowerLabelEStringParserRuleCall_10_1_0 = (RuleCall)cLowerLabelAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cUpperLabelKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cUpperLabelAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cUpperLabelEStringParserRuleCall_11_1_0 = (RuleCall)cUpperLabelAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cDependsOnKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cDependsOnAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_12_1_0 = (CrossReference)cDependsOnAssignment_12_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_12_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_12_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Scale:
		//	required?="required"? "Scale" "{" ("title" title=EString)? ("description" description=EString)? ("id" id=EString)?
		//	"lower" lower=EInt "upper" upper=EInt ("lowerLabel" lowerLabel=EString)? ("upperLabel" upperLabel=EString)?
		//	("dependsOn" dependsOn=[Answer|EString])? "}";
		public ParserRule getRule() { return rule; }

		//required?="required"? "Scale" "{" ("title" title=EString)? ("description" description=EString)? ("id" id=EString)?
		//"lower" lower=EInt "upper" upper=EInt ("lowerLabel" lowerLabel=EString)? ("upperLabel" upperLabel=EString)?
		//("dependsOn" dependsOn=[Answer|EString])? "}"
		public Group getGroup() { return cGroup; }

		//required?="required"?
		public Assignment getRequiredAssignment_0() { return cRequiredAssignment_0; }

		//"required"
		public Keyword getRequiredRequiredKeyword_0_0() { return cRequiredRequiredKeyword_0_0; }

		//"Scale"
		public Keyword getScaleKeyword_1() { return cScaleKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("title" title=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"title"
		public Keyword getTitleKeyword_3_0() { return cTitleKeyword_3_0; }

		//title=EString
		public Assignment getTitleAssignment_3_1() { return cTitleAssignment_3_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_3_1_0() { return cTitleEStringParserRuleCall_3_1_0; }

		//("description" description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//("id" id=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//id=EString
		public Assignment getIdAssignment_5_1() { return cIdAssignment_5_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_5_1_0() { return cIdEStringParserRuleCall_5_1_0; }

		//"lower"
		public Keyword getLowerKeyword_6() { return cLowerKeyword_6; }

		//lower=EInt
		public Assignment getLowerAssignment_7() { return cLowerAssignment_7; }

		//EInt
		public RuleCall getLowerEIntParserRuleCall_7_0() { return cLowerEIntParserRuleCall_7_0; }

		//"upper"
		public Keyword getUpperKeyword_8() { return cUpperKeyword_8; }

		//upper=EInt
		public Assignment getUpperAssignment_9() { return cUpperAssignment_9; }

		//EInt
		public RuleCall getUpperEIntParserRuleCall_9_0() { return cUpperEIntParserRuleCall_9_0; }

		//("lowerLabel" lowerLabel=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"lowerLabel"
		public Keyword getLowerLabelKeyword_10_0() { return cLowerLabelKeyword_10_0; }

		//lowerLabel=EString
		public Assignment getLowerLabelAssignment_10_1() { return cLowerLabelAssignment_10_1; }

		//EString
		public RuleCall getLowerLabelEStringParserRuleCall_10_1_0() { return cLowerLabelEStringParserRuleCall_10_1_0; }

		//("upperLabel" upperLabel=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"upperLabel"
		public Keyword getUpperLabelKeyword_11_0() { return cUpperLabelKeyword_11_0; }

		//upperLabel=EString
		public Assignment getUpperLabelAssignment_11_1() { return cUpperLabelAssignment_11_1; }

		//EString
		public RuleCall getUpperLabelEStringParserRuleCall_11_1_0() { return cUpperLabelEStringParserRuleCall_11_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_12() { return cGroup_12; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_12_0() { return cDependsOnKeyword_12_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_12_1() { return cDependsOnAssignment_12_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_12_1_0() { return cDependsOnAnswerCrossReference_12_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_12_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_12_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRequiredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRequiredRequiredKeyword_0_0 = (Keyword)cRequiredAssignment_0.eContents().get(0);
		private final Assignment cOtherAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOtherOtherKeyword_1_0 = (Keyword)cOtherAssignment_1.eContents().get(0);
		private final Assignment cMultipleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cMultipleMultipleKeyword_2_0 = (Keyword)cMultipleAssignment_2.eContents().get(0);
		private final Keyword cTableKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIdKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIdAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_7_1_0 = (RuleCall)cIdAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDependsOnKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDependsOnAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cDependsOnAnswerCrossReference_8_1_0 = (CrossReference)cDependsOnAssignment_8_1.eContents().get(0);
		private final RuleCall cDependsOnAnswerEStringParserRuleCall_8_1_0_1 = (RuleCall)cDependsOnAnswerCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTemplateKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTemplateAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cTemplateOptionCrossReference_9_1_0 = (CrossReference)cTemplateAssignment_9_1.eContents().get(0);
		private final RuleCall cTemplateOptionEStringParserRuleCall_9_1_0_1 = (RuleCall)cTemplateOptionCrossReference_9_1_0.eContents().get(1);
		private final Keyword cOptionsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cOptionsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cOptionsOptionParserRuleCall_12_0 = (RuleCall)cOptionsAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cOptionsAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cOptionsOptionParserRuleCall_13_1_0 = (RuleCall)cOptionsAssignment_13_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cQuestionsKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cQuestionsAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cQuestionsTableQuestionParserRuleCall_17_0 = (RuleCall)cQuestionsAssignment_17.eContents().get(0);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cCommaKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Assignment cQuestionsAssignment_18_1 = (Assignment)cGroup_18.eContents().get(1);
		private final RuleCall cQuestionsTableQuestionParserRuleCall_18_1_0 = (RuleCall)cQuestionsAssignment_18_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cTableOptionsKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cLeftCurlyBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cTableOptionsAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cTableOptionsOptionParserRuleCall_22_0 = (RuleCall)cTableOptionsAssignment_22.eContents().get(0);
		private final Group cGroup_23 = (Group)cGroup.eContents().get(23);
		private final Keyword cCommaKeyword_23_0 = (Keyword)cGroup_23.eContents().get(0);
		private final Assignment cTableOptionsAssignment_23_1 = (Assignment)cGroup_23.eContents().get(1);
		private final RuleCall cTableOptionsOptionParserRuleCall_23_1_0 = (RuleCall)cTableOptionsAssignment_23_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cRightCurlyBracketKeyword_25 = (Keyword)cGroup.eContents().get(25);
		
		//Table:
		//	required?="required"? other?="other"? multiple?="multiple"? "Table" "{" ("title" title=EString)? ("description"
		//	description=EString)? ("id" id=EString)? ("dependsOn" dependsOn=[Answer|EString])? ("template"
		//	template=[Option|EString])? "options" "{" options+=Option ("," options+=Option)* "}" "questions" "{"
		//	questions+=TableQuestion ("," questions+=TableQuestion)* "}" "tableOptions" "{" tableOptions+=Option (","
		//	tableOptions+=Option)* "}" "}";
		public ParserRule getRule() { return rule; }

		//required?="required"? other?="other"? multiple?="multiple"? "Table" "{" ("title" title=EString)? ("description"
		//description=EString)? ("id" id=EString)? ("dependsOn" dependsOn=[Answer|EString])? ("template"
		//template=[Option|EString])? "options" "{" options+=Option ("," options+=Option)* "}" "questions" "{"
		//questions+=TableQuestion ("," questions+=TableQuestion)* "}" "tableOptions" "{" tableOptions+=Option (","
		//tableOptions+=Option)* "}" "}"
		public Group getGroup() { return cGroup; }

		//required?="required"?
		public Assignment getRequiredAssignment_0() { return cRequiredAssignment_0; }

		//"required"
		public Keyword getRequiredRequiredKeyword_0_0() { return cRequiredRequiredKeyword_0_0; }

		//other?="other"?
		public Assignment getOtherAssignment_1() { return cOtherAssignment_1; }

		//"other"
		public Keyword getOtherOtherKeyword_1_0() { return cOtherOtherKeyword_1_0; }

		//multiple?="multiple"?
		public Assignment getMultipleAssignment_2() { return cMultipleAssignment_2; }

		//"multiple"
		public Keyword getMultipleMultipleKeyword_2_0() { return cMultipleMultipleKeyword_2_0; }

		//"Table"
		public Keyword getTableKeyword_3() { return cTableKeyword_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("description" description=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"description"
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }

		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }

		//("id" id=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"id"
		public Keyword getIdKeyword_7_0() { return cIdKeyword_7_0; }

		//id=EString
		public Assignment getIdAssignment_7_1() { return cIdAssignment_7_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_7_1_0() { return cIdEStringParserRuleCall_7_1_0; }

		//("dependsOn" dependsOn=[Answer|EString])?
		public Group getGroup_8() { return cGroup_8; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_8_0() { return cDependsOnKeyword_8_0; }

		//dependsOn=[Answer|EString]
		public Assignment getDependsOnAssignment_8_1() { return cDependsOnAssignment_8_1; }

		//[Answer|EString]
		public CrossReference getDependsOnAnswerCrossReference_8_1_0() { return cDependsOnAnswerCrossReference_8_1_0; }

		//EString
		public RuleCall getDependsOnAnswerEStringParserRuleCall_8_1_0_1() { return cDependsOnAnswerEStringParserRuleCall_8_1_0_1; }

		//("template" template=[Option|EString])?
		public Group getGroup_9() { return cGroup_9; }

		//"template"
		public Keyword getTemplateKeyword_9_0() { return cTemplateKeyword_9_0; }

		//template=[Option|EString]
		public Assignment getTemplateAssignment_9_1() { return cTemplateAssignment_9_1; }

		//[Option|EString]
		public CrossReference getTemplateOptionCrossReference_9_1_0() { return cTemplateOptionCrossReference_9_1_0; }

		//EString
		public RuleCall getTemplateOptionEStringParserRuleCall_9_1_0_1() { return cTemplateOptionEStringParserRuleCall_9_1_0_1; }

		//"options"
		public Keyword getOptionsKeyword_10() { return cOptionsKeyword_10; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }

		//options+=Option
		public Assignment getOptionsAssignment_12() { return cOptionsAssignment_12; }

		//Option
		public RuleCall getOptionsOptionParserRuleCall_12_0() { return cOptionsOptionParserRuleCall_12_0; }

		//("," options+=Option)*
		public Group getGroup_13() { return cGroup_13; }

		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }

		//options+=Option
		public Assignment getOptionsAssignment_13_1() { return cOptionsAssignment_13_1; }

		//Option
		public RuleCall getOptionsOptionParserRuleCall_13_1_0() { return cOptionsOptionParserRuleCall_13_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }

		//"questions"
		public Keyword getQuestionsKeyword_15() { return cQuestionsKeyword_15; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_16() { return cLeftCurlyBracketKeyword_16; }

		//questions+=TableQuestion
		public Assignment getQuestionsAssignment_17() { return cQuestionsAssignment_17; }

		//TableQuestion
		public RuleCall getQuestionsTableQuestionParserRuleCall_17_0() { return cQuestionsTableQuestionParserRuleCall_17_0; }

		//("," questions+=TableQuestion)*
		public Group getGroup_18() { return cGroup_18; }

		//","
		public Keyword getCommaKeyword_18_0() { return cCommaKeyword_18_0; }

		//questions+=TableQuestion
		public Assignment getQuestionsAssignment_18_1() { return cQuestionsAssignment_18_1; }

		//TableQuestion
		public RuleCall getQuestionsTableQuestionParserRuleCall_18_1_0() { return cQuestionsTableQuestionParserRuleCall_18_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }

		//"tableOptions"
		public Keyword getTableOptionsKeyword_20() { return cTableOptionsKeyword_20; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_21() { return cLeftCurlyBracketKeyword_21; }

		//tableOptions+=Option
		public Assignment getTableOptionsAssignment_22() { return cTableOptionsAssignment_22; }

		//Option
		public RuleCall getTableOptionsOptionParserRuleCall_22_0() { return cTableOptionsOptionParserRuleCall_22_0; }

		//("," tableOptions+=Option)*
		public Group getGroup_23() { return cGroup_23; }

		//","
		public Keyword getCommaKeyword_23_0() { return cCommaKeyword_23_0; }

		//tableOptions+=Option
		public Assignment getTableOptionsAssignment_23_1() { return cTableOptionsAssignment_23_1; }

		//Option
		public RuleCall getTableOptionsOptionParserRuleCall_23_1_0() { return cTableOptionsOptionParserRuleCall_23_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_24() { return cRightCurlyBracketKeyword_24; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_25() { return cRightCurlyBracketKeyword_25; }
	}

	public class Option_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Option_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOptionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOptionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Option_Impl returns Option:
		//	{Option} "Option";
		public ParserRule getRule() { return rule; }

		//{Option} "Option"
		public Group getGroup() { return cGroup; }

		//{Option}
		public Action getOptionAction_0() { return cOptionAction_0; }

		//"Option"
		public Keyword getOptionKeyword_1() { return cOptionKeyword_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class TableQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TableQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTableQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTitleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTitleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTitleEStringParserRuleCall_3_0 = (RuleCall)cTitleAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TableQuestion:
		//	"TableQuestion" "{" "title" title=EString "}";
		public ParserRule getRule() { return rule; }

		//"TableQuestion" "{" "title" title=EString "}"
		public Group getGroup() { return cGroup; }

		//"TableQuestion"
		public Keyword getTableQuestionKeyword_0() { return cTableQuestionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"title"
		public Keyword getTitleKeyword_2() { return cTitleKeyword_2; }

		//title=EString
		public Assignment getTitleAssignment_3() { return cTitleAssignment_3; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_3_0() { return cTitleEStringParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private SurveyElements pSurvey;
	private ItemElements pItem;
	private QuestionElements pQuestion;
	private OptionElements pOption;
	private EStringElements pEString;
	private AnswerTemplateElements pAnswerTemplate;
	private AnswerElements pAnswer;
	private EBooleanElements pEBoolean;
	private GroupElements pGroup;
	private SingleElements pSingle;
	private MultipleElements pMultiple;
	private TextElements pText;
	private DateElements pDate;
	private NumberElements pNumber;
	private ScaleElements pScale;
	private TableElements pTable;
	private Option_ImplElements pOption_Impl;
	private EIntElements pEInt;
	private TableQuestionElements pTableQuestion;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.itu.smdp.survey.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Survey:
	//	{Survey} "Survey" "{" ("title" title=EString)? ("description" description=EString)? ("items" "{" items+=Item (","
	//	items+=Item)* "}")? ("templates" "{" templates+=AnswerTemplate ("," templates+=AnswerTemplate)* "}")? "}";
	public SurveyElements getSurveyAccess() {
		return (pSurvey != null) ? pSurvey : (pSurvey = new SurveyElements());
	}
	
	public ParserRule getSurveyRule() {
		return getSurveyAccess().getRule();
	}

	//Item:
	//	Group | Single | Multiple | Text | Date | Number | Scale | Table;
	public ItemElements getItemAccess() {
		return (pItem != null) ? pItem : (pItem = new ItemElements());
	}
	
	public ParserRule getItemRule() {
		return getItemAccess().getRule();
	}

	//Question:
	//	Single | Multiple | Text | Date | Number | Scale | Table;
	public QuestionElements getQuestionAccess() {
		return (pQuestion != null) ? pQuestion : (pQuestion = new QuestionElements());
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}

	//Option:
	//	Option_Impl | Answer | AnswerTemplate;
	public OptionElements getOptionAccess() {
		return (pOption != null) ? pOption : (pOption = new OptionElements());
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//AnswerTemplate:
	//	"AnswerTemplate" "{" "id" id=EString "answers" "{" answers+=Answer ("," answers+=Answer)* "}" "}";
	public AnswerTemplateElements getAnswerTemplateAccess() {
		return (pAnswerTemplate != null) ? pAnswerTemplate : (pAnswerTemplate = new AnswerTemplateElements());
	}
	
	public ParserRule getAnswerTemplateRule() {
		return getAnswerTemplateAccess().getRule();
	}

	//Answer:
	//	"Answer" "{" ("id" id=EString)? "label" label=EString "}";
	public AnswerElements getAnswerAccess() {
		return (pAnswer != null) ? pAnswer : (pAnswer = new AnswerElements());
	}
	
	public ParserRule getAnswerRule() {
		return getAnswerAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//Group:
	//	required?="required"? "Group" "{" ("title" title=EString)? ("description" description=EString)? ("dependsOn"
	//	dependsOn=[Answer|EString])? "questions" "{" questions+=Question ("," questions+=Question)* "}" "}";
	public GroupElements getGroupAccess() {
		return (pGroup != null) ? pGroup : (pGroup = new GroupElements());
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}

	//Single:
	//	required?="required"? other?="other"? "Single" "{" ("title" title=EString)? ("description" description=EString)? ("id"
	//	id=EString)? ("dependsOn" dependsOn=[Answer|EString])? ("template" template=[Option|EString])? "options" "{"
	//	options+=Option ("," options+=Option)* "}" "}";
	public SingleElements getSingleAccess() {
		return (pSingle != null) ? pSingle : (pSingle = new SingleElements());
	}
	
	public ParserRule getSingleRule() {
		return getSingleAccess().getRule();
	}

	//Multiple:
	//	required?="required"? other?="other"? showLimits?="showLimits"? "Multiple" "{" ("title" title=EString)? ("description"
	//	description=EString)? ("id" id=EString)? ("lower" lower=EInt)? ("upper" upper=EInt)? ("dependsOn"
	//	dependsOn=[Answer|EString])? ("template" template=[Option|EString])? "options" "{" options+=Option (","
	//	options+=Option)* "}" "}";
	public MultipleElements getMultipleAccess() {
		return (pMultiple != null) ? pMultiple : (pMultiple = new MultipleElements());
	}
	
	public ParserRule getMultipleRule() {
		return getMultipleAccess().getRule();
	}

	//Text:
	//	{Text} required?="required"? multiline?="multiline"? "Text" "{" ("title" title=EString)? ("description"
	//	description=EString)? ("id" id=EString)? ("dependsOn" dependsOn=[Answer|EString])? "}";
	public TextElements getTextAccess() {
		return (pText != null) ? pText : (pText = new TextElements());
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}

	//Date:
	//	{Date} required?="required"? day?="day"? month?="month"? year?="year"? "Date" "{" ("title" title=EString)?
	//	("description" description=EString)? ("id" id=EString)? ("from" from=EString)? ("to" to=EString)? ("dependsOn"
	//	dependsOn=[Answer|EString])? "}";
	public DateElements getDateAccess() {
		return (pDate != null) ? pDate : (pDate = new DateElements());
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//Number:
	//	{Number} required?="required"? showLimits?="showLimits"? "Number" "{" ("title" title=EString)? ("description"
	//	description=EString)? ("id" id=EString)? ("lower" lower=EInt)? ("upper" upper=EInt)? ("dependsOn"
	//	dependsOn=[Answer|EString])? "}";
	public NumberElements getNumberAccess() {
		return (pNumber != null) ? pNumber : (pNumber = new NumberElements());
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//Scale:
	//	required?="required"? "Scale" "{" ("title" title=EString)? ("description" description=EString)? ("id" id=EString)?
	//	"lower" lower=EInt "upper" upper=EInt ("lowerLabel" lowerLabel=EString)? ("upperLabel" upperLabel=EString)?
	//	("dependsOn" dependsOn=[Answer|EString])? "}";
	public ScaleElements getScaleAccess() {
		return (pScale != null) ? pScale : (pScale = new ScaleElements());
	}
	
	public ParserRule getScaleRule() {
		return getScaleAccess().getRule();
	}

	//Table:
	//	required?="required"? other?="other"? multiple?="multiple"? "Table" "{" ("title" title=EString)? ("description"
	//	description=EString)? ("id" id=EString)? ("dependsOn" dependsOn=[Answer|EString])? ("template"
	//	template=[Option|EString])? "options" "{" options+=Option ("," options+=Option)* "}" "questions" "{"
	//	questions+=TableQuestion ("," questions+=TableQuestion)* "}" "tableOptions" "{" tableOptions+=Option (","
	//	tableOptions+=Option)* "}" "}";
	public TableElements getTableAccess() {
		return (pTable != null) ? pTable : (pTable = new TableElements());
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}

	//Option_Impl returns Option:
	//	{Option} "Option";
	public Option_ImplElements getOption_ImplAccess() {
		return (pOption_Impl != null) ? pOption_Impl : (pOption_Impl = new Option_ImplElements());
	}
	
	public ParserRule getOption_ImplRule() {
		return getOption_ImplAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//TableQuestion:
	//	"TableQuestion" "{" "title" title=EString "}";
	public TableQuestionElements getTableQuestionAccess() {
		return (pTableQuestion != null) ? pTableQuestion : (pTableQuestion = new TableQuestionElements());
	}
	
	public ParserRule getTableQuestionRule() {
		return getTableQuestionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
