/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.ui.contentassist;

import dk.itu.smdp.survey.ui.contentassist.AbstractDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
