/*
* generated by Xtext
*/
package dk.itu.smdp.survey.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.itu.smdp.survey.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {
	
	@Inject
	private DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.itu.smdp.survey.ui.contentassist.antlr.internal.InternalDslParser createParser() {
		dk.itu.smdp.survey.ui.contentassist.antlr.internal.InternalDslParser result = new dk.itu.smdp.survey.ui.contentassist.antlr.internal.InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSurveyAccess().getAlternatives_1_3(), "rule__Survey__Alternatives_1_3");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getItemAccess().getAlternatives(), "rule__Item__Alternatives");
					put(grammarAccess.getQuestionAccess().getAlternatives(), "rule__Question__Alternatives");
					put(grammarAccess.getOptionAccess().getAlternatives(), "rule__Option__Alternatives");
					put(grammarAccess.getTextAccess().getAlternatives_2_5(), "rule__Text__Alternatives_2_5");
					put(grammarAccess.getTextAccess().getMultilineAlternatives_2_5_2_0(), "rule__Text__MultilineAlternatives_2_5_2_0");
					put(grammarAccess.getDateAccess().getShowLimitsAlternatives_2_6_0(), "rule__Date__ShowLimitsAlternatives_2_6_0");
					put(grammarAccess.getNumberAccess().getShowLimitsAlternatives_2_7_0(), "rule__Number__ShowLimitsAlternatives_2_7_0");
					put(grammarAccess.getSingleAccess().getAlternatives(), "rule__Single__Alternatives");
					put(grammarAccess.getSingleWithOptionsAccess().getAlternatives_1_5(), "rule__SingleWithOptions__Alternatives_1_5");
					put(grammarAccess.getSingleWithOptionsAccess().getOtherAlternatives_1_5_0_0(), "rule__SingleWithOptions__OtherAlternatives_1_5_0_0");
					put(grammarAccess.getSingleRefAccess().getAlternatives_1_5(), "rule__SingleRef__Alternatives_1_5");
					put(grammarAccess.getSingleRefAccess().getOtherAlternatives_1_5_0_0(), "rule__SingleRef__OtherAlternatives_1_5_0_0");
					put(grammarAccess.getMultipleAccess().getAlternatives(), "rule__Multiple__Alternatives");
					put(grammarAccess.getMultipleWithOptionsAccess().getShowLimitsAlternatives_1_8_0(), "rule__MultipleWithOptions__ShowLimitsAlternatives_1_8_0");
					put(grammarAccess.getMultipleRefAccess().getShowLimitsAlternatives_1_8_0(), "rule__MultipleRef__ShowLimitsAlternatives_1_8_0");
					put(grammarAccess.getTableAccess().getAlternatives_1_5(), "rule__Table__Alternatives_1_5");
					put(grammarAccess.getTableAccess().getAlternatives_4(), "rule__Table__Alternatives_4");
					put(grammarAccess.getDEP_IDAccess().getAlternatives(), "rule__DEP_ID__Alternatives");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup_1(), "rule__Survey__Group_1__0");
					put(grammarAccess.getSurveyAccess().getGroup_1_1_0(), "rule__Survey__Group_1_1_0__0");
					put(grammarAccess.getSurveyAccess().getGroup_1_1_1(), "rule__Survey__Group_1_1_1__0");
					put(grammarAccess.getSurveyAccess().getGroup_1_1_2(), "rule__Survey__Group_1_1_2__0");
					put(grammarAccess.getAnswerTemplateAccess().getGroup(), "rule__AnswerTemplate__Group__0");
					put(grammarAccess.getAnswerAccess().getGroup(), "rule__Answer__Group__0");
					put(grammarAccess.getAnswerAccess().getGroup_1(), "rule__Answer__Group_1__0");
					put(grammarAccess.getGroupAccess().getGroup(), "rule__Group__Group__0");
					put(grammarAccess.getGroupAccess().getGroup_1_0(), "rule__Group__Group_1_0__0");
					put(grammarAccess.getGroupAccess().getGroup_1_1(), "rule__Group__Group_1_1__0");
					put(grammarAccess.getGroupAccess().getGroup_1_2(), "rule__Group__Group_1_2__0");
					put(grammarAccess.getGroupAccess().getGroup_1_3(), "rule__Group__Group_1_3__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getTextAccess().getGroup_2_0(), "rule__Text__Group_2_0__0");
					put(grammarAccess.getTextAccess().getGroup_2_1(), "rule__Text__Group_2_1__0");
					put(grammarAccess.getTextAccess().getGroup_2_2(), "rule__Text__Group_2_2__0");
					put(grammarAccess.getTextAccess().getGroup_2_3(), "rule__Text__Group_2_3__0");
					put(grammarAccess.getScaleAccess().getGroup(), "rule__Scale__Group__0");
					put(grammarAccess.getScaleAccess().getGroup_1_0(), "rule__Scale__Group_1_0__0");
					put(grammarAccess.getScaleAccess().getGroup_1_1(), "rule__Scale__Group_1_1__0");
					put(grammarAccess.getScaleAccess().getGroup_1_2(), "rule__Scale__Group_1_2__0");
					put(grammarAccess.getScaleAccess().getGroup_1_3(), "rule__Scale__Group_1_3__0");
					put(grammarAccess.getScaleAccess().getGroup_1_4(), "rule__Scale__Group_1_4__0");
					put(grammarAccess.getScaleAccess().getGroup_1_5(), "rule__Scale__Group_1_5__0");
					put(grammarAccess.getScaleAccess().getGroup_1_6(), "rule__Scale__Group_1_6__0");
					put(grammarAccess.getScaleAccess().getGroup_1_7(), "rule__Scale__Group_1_7__0");
					put(grammarAccess.getDateAccess().getGroup(), "rule__Date__Group__0");
					put(grammarAccess.getDateAccess().getGroup_2_0(), "rule__Date__Group_2_0__0");
					put(grammarAccess.getDateAccess().getGroup_2_1(), "rule__Date__Group_2_1__0");
					put(grammarAccess.getDateAccess().getGroup_2_2(), "rule__Date__Group_2_2__0");
					put(grammarAccess.getDateAccess().getGroup_2_3(), "rule__Date__Group_2_3__0");
					put(grammarAccess.getDateAccess().getGroup_2_4(), "rule__Date__Group_2_4__0");
					put(grammarAccess.getDateAccess().getGroup_2_5(), "rule__Date__Group_2_5__0");
					put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
					put(grammarAccess.getNumberAccess().getGroup_2_0(), "rule__Number__Group_2_0__0");
					put(grammarAccess.getNumberAccess().getGroup_2_1(), "rule__Number__Group_2_1__0");
					put(grammarAccess.getNumberAccess().getGroup_2_2(), "rule__Number__Group_2_2__0");
					put(grammarAccess.getNumberAccess().getGroup_2_3(), "rule__Number__Group_2_3__0");
					put(grammarAccess.getNumberAccess().getGroup_2_4(), "rule__Number__Group_2_4__0");
					put(grammarAccess.getNumberAccess().getGroup_2_5(), "rule__Number__Group_2_5__0");
					put(grammarAccess.getSingleWithOptionsAccess().getGroup(), "rule__SingleWithOptions__Group__0");
					put(grammarAccess.getSingleWithOptionsAccess().getGroup_1_0(), "rule__SingleWithOptions__Group_1_0__0");
					put(grammarAccess.getSingleWithOptionsAccess().getGroup_1_1(), "rule__SingleWithOptions__Group_1_1__0");
					put(grammarAccess.getSingleWithOptionsAccess().getGroup_1_2(), "rule__SingleWithOptions__Group_1_2__0");
					put(grammarAccess.getSingleWithOptionsAccess().getGroup_1_3(), "rule__SingleWithOptions__Group_1_3__0");
					put(grammarAccess.getSingleWithOptionsAccess().getGroup_1_5_1(), "rule__SingleWithOptions__Group_1_5_1__0");
					put(grammarAccess.getSingleRefAccess().getGroup(), "rule__SingleRef__Group__0");
					put(grammarAccess.getSingleRefAccess().getGroup_1_0(), "rule__SingleRef__Group_1_0__0");
					put(grammarAccess.getSingleRefAccess().getGroup_1_1(), "rule__SingleRef__Group_1_1__0");
					put(grammarAccess.getSingleRefAccess().getGroup_1_2(), "rule__SingleRef__Group_1_2__0");
					put(grammarAccess.getSingleRefAccess().getGroup_1_3(), "rule__SingleRef__Group_1_3__0");
					put(grammarAccess.getSingleRefAccess().getGroup_1_5_1(), "rule__SingleRef__Group_1_5_1__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup(), "rule__MultipleWithOptions__Group__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup_1_0(), "rule__MultipleWithOptions__Group_1_0__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup_1_1(), "rule__MultipleWithOptions__Group_1_1__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup_1_2(), "rule__MultipleWithOptions__Group_1_2__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup_1_3(), "rule__MultipleWithOptions__Group_1_3__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup_1_4(), "rule__MultipleWithOptions__Group_1_4__0");
					put(grammarAccess.getMultipleWithOptionsAccess().getGroup_1_5(), "rule__MultipleWithOptions__Group_1_5__0");
					put(grammarAccess.getMultipleRefAccess().getGroup(), "rule__MultipleRef__Group__0");
					put(grammarAccess.getMultipleRefAccess().getGroup_1_0(), "rule__MultipleRef__Group_1_0__0");
					put(grammarAccess.getMultipleRefAccess().getGroup_1_1(), "rule__MultipleRef__Group_1_1__0");
					put(grammarAccess.getMultipleRefAccess().getGroup_1_2(), "rule__MultipleRef__Group_1_2__0");
					put(grammarAccess.getMultipleRefAccess().getGroup_1_3(), "rule__MultipleRef__Group_1_3__0");
					put(grammarAccess.getMultipleRefAccess().getGroup_1_4(), "rule__MultipleRef__Group_1_4__0");
					put(grammarAccess.getMultipleRefAccess().getGroup_1_5(), "rule__MultipleRef__Group_1_5__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getTableAccess().getGroup_1_0(), "rule__Table__Group_1_0__0");
					put(grammarAccess.getTableAccess().getGroup_1_1(), "rule__Table__Group_1_1__0");
					put(grammarAccess.getTableAccess().getGroup_1_2(), "rule__Table__Group_1_2__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getAnswerTemplateRefAccess().getGroup(), "rule__AnswerTemplateRef__Group__0");
					put(grammarAccess.getAnswerTemplateRefAttrAccess().getGroup(), "rule__AnswerTemplateRefAttr__Group__0");
					put(grammarAccess.getTableQuestionAccess().getGroup(), "rule__TableQuestion__Group__0");
					put(grammarAccess.getTableQuestionAccess().getGroup_1_0(), "rule__TableQuestion__Group_1_0__0");
					put(grammarAccess.getSurveyAccess().getTitleAssignment_1_1_0_1(), "rule__Survey__TitleAssignment_1_1_0_1");
					put(grammarAccess.getSurveyAccess().getDescriptionAssignment_1_1_1_1(), "rule__Survey__DescriptionAssignment_1_1_1_1");
					put(grammarAccess.getSurveyAccess().getNameAssignment_1_1_2_1(), "rule__Survey__NameAssignment_1_1_2_1");
					put(grammarAccess.getSurveyAccess().getItemsAssignment_1_3_0(), "rule__Survey__ItemsAssignment_1_3_0");
					put(grammarAccess.getSurveyAccess().getTemplatesAssignment_1_3_1(), "rule__Survey__TemplatesAssignment_1_3_1");
					put(grammarAccess.getAnswerTemplateAccess().getNameAssignment_2(), "rule__AnswerTemplate__NameAssignment_2");
					put(grammarAccess.getAnswerTemplateAccess().getAnswersAssignment_5(), "rule__AnswerTemplate__AnswersAssignment_5");
					put(grammarAccess.getAnswerAccess().getNameAssignment_1_1(), "rule__Answer__NameAssignment_1_1");
					put(grammarAccess.getAnswerAccess().getTitleAssignment_3(), "rule__Answer__TitleAssignment_3");
					put(grammarAccess.getGroupAccess().getTitleAssignment_1_0_1(), "rule__Group__TitleAssignment_1_0_1");
					put(grammarAccess.getGroupAccess().getNameAssignment_1_1_1(), "rule__Group__NameAssignment_1_1_1");
					put(grammarAccess.getGroupAccess().getDescriptionAssignment_1_2_1(), "rule__Group__DescriptionAssignment_1_2_1");
					put(grammarAccess.getGroupAccess().getDependsOnAssignment_1_3_1(), "rule__Group__DependsOnAssignment_1_3_1");
					put(grammarAccess.getGroupAccess().getRequiredAssignment_1_4(), "rule__Group__RequiredAssignment_1_4");
					put(grammarAccess.getGroupAccess().getQuestionsAssignment_3(), "rule__Group__QuestionsAssignment_3");
					put(grammarAccess.getTextAccess().getTitleAssignment_2_0_1(), "rule__Text__TitleAssignment_2_0_1");
					put(grammarAccess.getTextAccess().getDescriptionAssignment_2_1_1(), "rule__Text__DescriptionAssignment_2_1_1");
					put(grammarAccess.getTextAccess().getNameAssignment_2_2_1(), "rule__Text__NameAssignment_2_2_1");
					put(grammarAccess.getTextAccess().getDependsOnAssignment_2_3_1(), "rule__Text__DependsOnAssignment_2_3_1");
					put(grammarAccess.getTextAccess().getRequiredAssignment_2_4(), "rule__Text__RequiredAssignment_2_4");
					put(grammarAccess.getTextAccess().getMultilineAssignment_2_5_2(), "rule__Text__MultilineAssignment_2_5_2");
					put(grammarAccess.getScaleAccess().getTitleAssignment_1_0_1(), "rule__Scale__TitleAssignment_1_0_1");
					put(grammarAccess.getScaleAccess().getDescriptionAssignment_1_1_1(), "rule__Scale__DescriptionAssignment_1_1_1");
					put(grammarAccess.getScaleAccess().getNameAssignment_1_2_1(), "rule__Scale__NameAssignment_1_2_1");
					put(grammarAccess.getScaleAccess().getMinAssignment_1_3_1(), "rule__Scale__MinAssignment_1_3_1");
					put(grammarAccess.getScaleAccess().getMaxAssignment_1_4_1(), "rule__Scale__MaxAssignment_1_4_1");
					put(grammarAccess.getScaleAccess().getMinLabelAssignment_1_5_1(), "rule__Scale__MinLabelAssignment_1_5_1");
					put(grammarAccess.getScaleAccess().getMaxLabelAssignment_1_6_1(), "rule__Scale__MaxLabelAssignment_1_6_1");
					put(grammarAccess.getScaleAccess().getDependsOnAssignment_1_7_1(), "rule__Scale__DependsOnAssignment_1_7_1");
					put(grammarAccess.getScaleAccess().getRequiredAssignment_1_8(), "rule__Scale__RequiredAssignment_1_8");
					put(grammarAccess.getDateAccess().getTitleAssignment_2_0_1(), "rule__Date__TitleAssignment_2_0_1");
					put(grammarAccess.getDateAccess().getDescriptionAssignment_2_1_1(), "rule__Date__DescriptionAssignment_2_1_1");
					put(grammarAccess.getDateAccess().getNameAssignment_2_2_1(), "rule__Date__NameAssignment_2_2_1");
					put(grammarAccess.getDateAccess().getStartAssignment_2_3_1(), "rule__Date__StartAssignment_2_3_1");
					put(grammarAccess.getDateAccess().getEndAssignment_2_4_1(), "rule__Date__EndAssignment_2_4_1");
					put(grammarAccess.getDateAccess().getDependsOnAssignment_2_5_1(), "rule__Date__DependsOnAssignment_2_5_1");
					put(grammarAccess.getDateAccess().getShowLimitsAssignment_2_6(), "rule__Date__ShowLimitsAssignment_2_6");
					put(grammarAccess.getDateAccess().getRequiredAssignment_2_7(), "rule__Date__RequiredAssignment_2_7");
					put(grammarAccess.getDateAccess().getDayAssignment_2_8(), "rule__Date__DayAssignment_2_8");
					put(grammarAccess.getDateAccess().getMonthAssignment_2_9(), "rule__Date__MonthAssignment_2_9");
					put(grammarAccess.getDateAccess().getYearAssignment_2_10(), "rule__Date__YearAssignment_2_10");
					put(grammarAccess.getNumberAccess().getTitleAssignment_2_0_1(), "rule__Number__TitleAssignment_2_0_1");
					put(grammarAccess.getNumberAccess().getDescriptionAssignment_2_1_1(), "rule__Number__DescriptionAssignment_2_1_1");
					put(grammarAccess.getNumberAccess().getNameAssignment_2_2_1(), "rule__Number__NameAssignment_2_2_1");
					put(grammarAccess.getNumberAccess().getMinAssignment_2_3_1(), "rule__Number__MinAssignment_2_3_1");
					put(grammarAccess.getNumberAccess().getMaxAssignment_2_4_1(), "rule__Number__MaxAssignment_2_4_1");
					put(grammarAccess.getNumberAccess().getDependsOnAssignment_2_5_1(), "rule__Number__DependsOnAssignment_2_5_1");
					put(grammarAccess.getNumberAccess().getRequiredAssignment_2_6(), "rule__Number__RequiredAssignment_2_6");
					put(grammarAccess.getNumberAccess().getShowLimitsAssignment_2_7(), "rule__Number__ShowLimitsAssignment_2_7");
					put(grammarAccess.getSingleWithOptionsAccess().getTitleAssignment_1_0_1(), "rule__SingleWithOptions__TitleAssignment_1_0_1");
					put(grammarAccess.getSingleWithOptionsAccess().getDescriptionAssignment_1_1_1(), "rule__SingleWithOptions__DescriptionAssignment_1_1_1");
					put(grammarAccess.getSingleWithOptionsAccess().getNameAssignment_1_2_1(), "rule__SingleWithOptions__NameAssignment_1_2_1");
					put(grammarAccess.getSingleWithOptionsAccess().getDependsOnAssignment_1_3_1(), "rule__SingleWithOptions__DependsOnAssignment_1_3_1");
					put(grammarAccess.getSingleWithOptionsAccess().getRequiredAssignment_1_4(), "rule__SingleWithOptions__RequiredAssignment_1_4");
					put(grammarAccess.getSingleWithOptionsAccess().getOtherAssignment_1_5_0(), "rule__SingleWithOptions__OtherAssignment_1_5_0");
					put(grammarAccess.getSingleWithOptionsAccess().getOtherLabelAssignment_1_5_1_1(), "rule__SingleWithOptions__OtherLabelAssignment_1_5_1_1");
					put(grammarAccess.getSingleWithOptionsAccess().getOptionsAssignment_3(), "rule__SingleWithOptions__OptionsAssignment_3");
					put(grammarAccess.getSingleRefAccess().getTitleAssignment_1_0_1(), "rule__SingleRef__TitleAssignment_1_0_1");
					put(grammarAccess.getSingleRefAccess().getDescriptionAssignment_1_1_1(), "rule__SingleRef__DescriptionAssignment_1_1_1");
					put(grammarAccess.getSingleRefAccess().getNameAssignment_1_2_1(), "rule__SingleRef__NameAssignment_1_2_1");
					put(grammarAccess.getSingleRefAccess().getDependsOnAssignment_1_3_1(), "rule__SingleRef__DependsOnAssignment_1_3_1");
					put(grammarAccess.getSingleRefAccess().getRequiredAssignment_1_4(), "rule__SingleRef__RequiredAssignment_1_4");
					put(grammarAccess.getSingleRefAccess().getOtherAssignment_1_5_0(), "rule__SingleRef__OtherAssignment_1_5_0");
					put(grammarAccess.getSingleRefAccess().getOtherLabelAssignment_1_5_1_1(), "rule__SingleRef__OtherLabelAssignment_1_5_1_1");
					put(grammarAccess.getSingleRefAccess().getOptionsAssignment_1_6(), "rule__SingleRef__OptionsAssignment_1_6");
					put(grammarAccess.getMultipleWithOptionsAccess().getTitleAssignment_1_0_1(), "rule__MultipleWithOptions__TitleAssignment_1_0_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getDescriptionAssignment_1_1_1(), "rule__MultipleWithOptions__DescriptionAssignment_1_1_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getNameAssignment_1_2_1(), "rule__MultipleWithOptions__NameAssignment_1_2_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getMinAssignment_1_3_1(), "rule__MultipleWithOptions__MinAssignment_1_3_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getMaxAssignment_1_4_1(), "rule__MultipleWithOptions__MaxAssignment_1_4_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getDependsOnAssignment_1_5_1(), "rule__MultipleWithOptions__DependsOnAssignment_1_5_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getRequiredAssignment_1_6(), "rule__MultipleWithOptions__RequiredAssignment_1_6");
					put(grammarAccess.getMultipleWithOptionsAccess().getOtherAssignment_1_7(), "rule__MultipleWithOptions__OtherAssignment_1_7");
					put(grammarAccess.getMultipleWithOptionsAccess().getShowLimitsAssignment_1_8(), "rule__MultipleWithOptions__ShowLimitsAssignment_1_8");
					put(grammarAccess.getMultipleWithOptionsAccess().getOptionsAssignment_3(), "rule__MultipleWithOptions__OptionsAssignment_3");
					put(grammarAccess.getMultipleRefAccess().getTitleAssignment_1_0_1(), "rule__MultipleRef__TitleAssignment_1_0_1");
					put(grammarAccess.getMultipleRefAccess().getDescriptionAssignment_1_1_1(), "rule__MultipleRef__DescriptionAssignment_1_1_1");
					put(grammarAccess.getMultipleRefAccess().getNameAssignment_1_2_1(), "rule__MultipleRef__NameAssignment_1_2_1");
					put(grammarAccess.getMultipleRefAccess().getMinAssignment_1_3_1(), "rule__MultipleRef__MinAssignment_1_3_1");
					put(grammarAccess.getMultipleRefAccess().getMaxAssignment_1_4_1(), "rule__MultipleRef__MaxAssignment_1_4_1");
					put(grammarAccess.getMultipleRefAccess().getDependsOnAssignment_1_5_1(), "rule__MultipleRef__DependsOnAssignment_1_5_1");
					put(grammarAccess.getMultipleRefAccess().getRequiredAssignment_1_6(), "rule__MultipleRef__RequiredAssignment_1_6");
					put(grammarAccess.getMultipleRefAccess().getOtherAssignment_1_7(), "rule__MultipleRef__OtherAssignment_1_7");
					put(grammarAccess.getMultipleRefAccess().getShowLimitsAssignment_1_8(), "rule__MultipleRef__ShowLimitsAssignment_1_8");
					put(grammarAccess.getMultipleRefAccess().getOptionsAssignment_1_9(), "rule__MultipleRef__OptionsAssignment_1_9");
					put(grammarAccess.getTableAccess().getTitleAssignment_1_0_1(), "rule__Table__TitleAssignment_1_0_1");
					put(grammarAccess.getTableAccess().getDescriptionAssignment_1_1_1(), "rule__Table__DescriptionAssignment_1_1_1");
					put(grammarAccess.getTableAccess().getDependsOnAssignment_1_2_1(), "rule__Table__DependsOnAssignment_1_2_1");
					put(grammarAccess.getTableAccess().getRequiredAssignment_1_3(), "rule__Table__RequiredAssignment_1_3");
					put(grammarAccess.getTableAccess().getOtherAssignment_1_4(), "rule__Table__OtherAssignment_1_4");
					put(grammarAccess.getTableAccess().getMultipleAssignment_1_5_1(), "rule__Table__MultipleAssignment_1_5_1");
					put(grammarAccess.getTableAccess().getOptionsAssignment_3_0(), "rule__Table__OptionsAssignment_3_0");
					put(grammarAccess.getTableAccess().getQuestionsAssignment_3_1(), "rule__Table__QuestionsAssignment_3_1");
					put(grammarAccess.getTableAccess().getOptionsAssignment_4_0(), "rule__Table__OptionsAssignment_4_0");
					put(grammarAccess.getTableAccess().getQuestionsAssignment_4_1(), "rule__Table__QuestionsAssignment_4_1");
					put(grammarAccess.getAnswerTemplateRefAccess().getTemplateAssignment_2(), "rule__AnswerTemplateRef__TemplateAssignment_2");
					put(grammarAccess.getAnswerTemplateRefAttrAccess().getTemplateAssignment_1(), "rule__AnswerTemplateRefAttr__TemplateAssignment_1");
					put(grammarAccess.getTableQuestionAccess().getNameAssignment_1_0_1(), "rule__TableQuestion__NameAssignment_1_0_1");
					put(grammarAccess.getTableQuestionAccess().getRequiredAssignment_1_1(), "rule__TableQuestion__RequiredAssignment_1_1");
					put(grammarAccess.getTableQuestionAccess().getTitleAssignment_3(), "rule__TableQuestion__TitleAssignment_3");
					put(grammarAccess.getSurveyAccess().getUnorderedGroup_1_1(), "rule__Survey__UnorderedGroup_1_1");
					put(grammarAccess.getGroupAccess().getUnorderedGroup_1(), "rule__Group__UnorderedGroup_1");
					put(grammarAccess.getTextAccess().getUnorderedGroup_2(), "rule__Text__UnorderedGroup_2");
					put(grammarAccess.getScaleAccess().getUnorderedGroup_1(), "rule__Scale__UnorderedGroup_1");
					put(grammarAccess.getDateAccess().getUnorderedGroup_2(), "rule__Date__UnorderedGroup_2");
					put(grammarAccess.getNumberAccess().getUnorderedGroup_2(), "rule__Number__UnorderedGroup_2");
					put(grammarAccess.getSingleWithOptionsAccess().getUnorderedGroup_1(), "rule__SingleWithOptions__UnorderedGroup_1");
					put(grammarAccess.getSingleRefAccess().getUnorderedGroup_1(), "rule__SingleRef__UnorderedGroup_1");
					put(grammarAccess.getMultipleWithOptionsAccess().getUnorderedGroup_1(), "rule__MultipleWithOptions__UnorderedGroup_1");
					put(grammarAccess.getMultipleRefAccess().getUnorderedGroup_1(), "rule__MultipleRef__UnorderedGroup_1");
					put(grammarAccess.getTableAccess().getUnorderedGroup_1(), "rule__Table__UnorderedGroup_1");
					put(grammarAccess.getTableAccess().getUnorderedGroup_3(), "rule__Table__UnorderedGroup_3");
					put(grammarAccess.getTableQuestionAccess().getUnorderedGroup_1(), "rule__TableQuestion__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.itu.smdp.survey.ui.contentassist.antlr.internal.InternalDslParser typedParser = (dk.itu.smdp.survey.ui.contentassist.antlr.internal.InternalDslParser) parser;
			typedParser.entryRuleSurvey();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT" };
	}
	
	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
